### ISSUE TITLE
Clarify the purpose of `rowKey` in the docs

### ISSUE THREAD

**Issue by julen** [reactabular/reactabular#166]
As I see the examples in the docs are making use of the `rowKey` prop, but there's no explanation whatsoever on what it is and why it is required — arguably one could guess that it might be related to React's [`key` prop for dynamic children](https://facebook.github.io/react/docs/multiple-components.html#dynamic-children).

By the way, after checking the source code, [it would seem `rowKey` is optional](https://github.com/reactabular/reactabular/blob/be28111b0e84ed713f660aa2618a7b84cfb1c08f/src/table/body.js#L23) (``key: `${r[rowKey] || i}-row` ``), although `propTypes` say the contrary.

It'd be great to have a clarification on this one. Thank you!

**Comment by bebraw** [comment]
Good point. I'll document it for the next release.

Essentially it's performance related. React uses keys to tell virtual DOM elements apart on change. Using index is the worst possible choice and I use the default only for arrays of items (excel example).
