### ISSUE TITLE
[rc6] Need help resolving things properly

### ISSUE THREAD

**Issue by skosch** [reactabular/reactabular#169]
Just testing out RC5/6, and having issues resolving things properly (but I may well be doing something wrong): I'm getting a ton of  errors à la
```
cra.dll.js:746 Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {__dataID__, year}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `BodyRow`.`
```
when I'm trying take care both of `property`-based path resolvers and explicit `resolve` handlers via
```
    const resolver = resolve.resolve({
      columns: this.state.columns,
      method: (row, column) => resolve.byFunction('cell.resolve')(
        resolve.nested(row, column),
        column
      )
    });
```
The underscore properties are added alright, but for some reason it still seems to want to use the nested objects as the resolved values. Can you help me diagnose the problem?

**Comment by skosch** [comment]
... so, if I add a formatter like this:
```
      cell: {
        property: 'myNestedDataObject',
        resolve: value => myNestedDataObject.someArray.length ? 'Present' : 'Absent',
        format: (value, {rowData}) => {
          return rowData._myNestedDataObject;
        }
      }
```
... then everything works as expected. Shouldn't that happen automatically whenever `resolve.byFunction` is used?

**Comment by bebraw** [comment]
Ah, I see now. I think we'll need to make `Table.Body` aware of the resolved values. So instead of passing regular value to `format`, we'll need to pass resolved one instead if it exists.

You can still access the original one through the data but I feel this is the right thing to do and it would fix your issue. I'll change this for the next release.

Thanks for the report!
