### ISSUE TITLE
[rc6] Keep data attributes during resolving

### ISSUE THREAD

**Issue by skosch** [reactabular/reactabular#170]
After running the resolver, only displayed values are left, thanks to this piece of code:
```
  return rows => rows.map(row => {
    let ret = {};

    resolvedColumns.forEach(column => {
      ret = {
        ...ret,
        ...method(row, column)
      };
    });

    return ret;
  });
```
... but I need the rest of my data, too. Crucially, I need an `id` field, which I don't want displayed, but which I need for my `onRow` click handler. 

The best compromise in terms of annoyance/performance may be to allow users to define phantom columns that don't get rendered.

In any case however, the `rowKey` should be kept around. It'll be `id` in most cases anyway.

**Comment by bebraw** [comment]
Yeah, good point. Maybe the right thing to do is to overlay the resolved data on top of the other. So extra `...`. I think I'll change the resolver that way.

Thanks for the report again.

**Comment by skosch** [comment]
Hm, this isn't really working for me yet. If I want to be able to use both resolver methods as you do in the example, i.e.
```javascript
    const resolver = resolve.resolve({
      columns: this.state.columns,
      method: (row, column) => resolve.byFunction('cell.resolve')(
        resolve.nested(row, column),
        column
      )
    });
```
then if no `property` is found (but only `resolve`),
1. `resolve.nested` should just return the whole thing, not just `{}`, and
2. `resolve.byFunction` will use `value = undefined`, which isn't exactly what people might expect.

The alternative would be to combine resolver methods differently: I've now switched to
```javascript
      method: (row, column) => {
        if (column.cell.resolve) {
          return resolve.byFunction('cell.resolve')(row, column);
        } else {
          return resolve.nested(row, column);
        }
      }
```
... but again this means I have to remember not to try and use `value` in my formatters, because it'll be undefined.

**Suggestion:** forget about the split between `property` and `resolve` and keep only one. If `typeof == 'function'`, call the function to get the resolved value; if it's a string, use `_.get`.

**Comment by skosch** [comment]
Actually, disregard what I just wrote. Of course the columns need `property` to know which data attribute to read their data from :see_no_evil: 

The issue remains, however, that there is no reliable way to resolve first by `property` (if it exists) and then by `resolve`, with the result of the `nested` pass getting passed in as `value`, without some convoluted back-and-forth:
```javascript
      method: (row, column) => {
        if (column.cell.resolve) {
          const resolvedByProperty = resolve.nested(row, column);
          if (has(resolvedByProperty, column.cell.property)) {
            const rowData = {
              ...row,
              ...resolvedByProperty
            };
            return resolve.byFunction('cell.resolve')(rowData, column);
          } else {
            console.warn("Could not resolve by property, value will be undefined!");
            return resolve.byFunction('cell.resolve')(row, column);
          }
        } else {
          return resolve.nested(row, column);
        }
      }
```
This does appear to work, but I'd be thrilled if some of this could be baked into the resolvers themselves.

**Comment by skosch** [comment]
**Another thing:** The rest of the data isn't kept around if a table uses *only* `property` columns. Just ran into that issue and was able to fix it by adding an identity resolver, but I shouldn't have to :)

**Comment by bebraw** [comment]
@skosch Can you open a separate issue and set up some kind of test case? Sounds like I'm missing a piece of logic to make the behavior nice.

> Another thing: The rest of the data isn't kept around if a table uses only property columns. Just ran into that issue and was able to fix it by adding an identity resolver, but I shouldn't have to :)

That sounds like an easy fix. I can probably write a test case just for that.

**Comment by bebraw** [comment]
@skosch Could you write test cases for the problematic bits? That would help a lot. I don't mind writing the implementation to match those.

**Comment by skosch** [comment]
I'll do my best, if it can wait until tomorrow afternoon – sorry, I'm a bit swamped with other stuff at the moment! And who knows, maybe it turns out I'm just using it wrong ... sorry about the delay anways!

**Comment by bebraw** [comment]
No worries. :+1:

**Comment by skosch** [comment]
Alright, here we go. I'm not gonna bother making a PR for this because I'm sure things will change anyways, but the following fails for me:
```javascript
  it('resolves using multiple resolvers and provides correct intermediate rowData', function () {
    const lastName = 'Demo';
    const columns = [
      {
        header: {
          label: 'Resolved value'
        },
        cell: {
          resolve: (value, {rowData}) => rowData.name.last + value,
          property: 'name.last'
        }
      }
    ];
    const rows = [
      {
        name: {
          last: lastName
        }
      }
    ];
    const expected = [
      {
        'name.last': lastName,
        '_name.last': lastName + lastName
      }
    ];
    const resolver = resolve({
      columns,
      method: (row, column) => byFunction('cell.resolve')(
        nested(row, column),
        column
      )
    });

    expect(resolver(rows)).to.deep.equal(expected);
  });
```
The one thing to take away here is that `byFunction` doesn't have access to `rowData`, because `nested` doesn't return any. Yes, `resolver.resolve` takes care of this on a higher level, but when we write custom combined resolvers we need to shepherd that data around manually – see my code sample a few posts up, which shows that it *can* work.

So you could a) document the requirement for explicit data copying, or b) reconsider how the pieces of the resolver puzzle should go together. I hope that helps!

**Comment by bebraw** [comment]
@skosch Thanks. Looks good. 👍
