### ISSUE TITLE
Updating sorting positions

### ISSUE THREAD

**Issue by skosch** [reactabular/reactabular#171]
So … users have been reporting to me that "the sorting is broken", which baffled me until they showed me what they meant. Turns out sorting isn't broken, but the fact that each subsequent click on a header adds a `sortingColumns` entry with higher `position` (i.e. lower priority) means that in practice, clicking on a header often doesn't have any visible effect – because any lower-position column will determine the order unless its data is degenerate.

I explained the position system – to lots of hmmms and cocked heads and furrowed brows – and was told that the intuitive expectation was instead that every click should make *that* column the lowest-position one, while all others' positions are incremented by one, such that every click has a visible effect and nothing *feels* broken.

Having spent time with the sorting code myself, I was totally unaware that this would be an issue for people, but I can see now that it may be worthwhile providing the option at least. Maybe the position-updating behaviour can be provided via a prop to `<Table.Header>` or something? Or maybe you have a better idea altogether? Looking forward to your thoughts.

**Comment by bebraw** [comment]
Yeah, I can see how that could be confusing to the users. I think you could solve this neatly by passing a custom `sort` function to `sorter`. Basically it does `sort(data, columnIndexList, orderList)` (lodash `orderBy`).

You could write a custom function like this:

```javascript
const customSort = (data, columnIndexList, orderList) =>  orderBy(data, columnIndexList.reverse(), orderList.reverse());
```

Note that `reverse()` mutates the original array so you might want to do something else instead but I think this should work for your case.

If we start getting a lot of feedback about this, maybe we can bake something in. I'm not too sold on custom props as I feel this is something better solved on logic level. That was one of the main goals of the redesign. I don't want to go back to flags and all that again. 👍

**Comment by skosch** [comment]
Brilliant, that works like a charm! (So well, in fact, that I think it deserves a mention in the docs :)

Thanks for the warning about `reverse()`, too. There's always `slice().reverse()`, but I don't even think that's necessary here. :+1:

**Comment by bebraw** [comment]
Yeah, I'll add a note. 👍

**Comment by skosch** [comment]
Hey, sorry, I do have to revisit this one. I've received complaints – there are situations in which the `reverse()` hack doesn't achieve the desired effect after all.

What I need, really, is this: when I click on a column with current `position: n`, that column is set to `position: 0` while all column positions between `0` and `n - 1` are incremented by one. That is extra code that needs to go into `by_columns.js` (or a sibling file) I'm afraid. 

If you're not interested in offering this functionality I can make a local version of `byColumns` for myself. Otherwise, I think it would be nice to give users the choice between `alwaysPrioritizeLastSort: true` or not. What do you think?

**Comment by bebraw** [comment]
I'm not that great fan of flags. I would accept a PR for another sort variant, though.

**Comment by skosch** [comment]
Sure thing. Any preference regarding the name?

**Comment by bebraw** [comment]
Not really. Propose something. 👍

**Comment by skosch** [comment]
Man, I'm having a hard time with this one. `byColumnsPrioritizeLastSorted` okay? It's a mouthful, I know ...

**Comment by bebraw** [comment]
Good enough. Merged. 👍
