### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by venkirocking2** [reactabular/reactabular#175]
C:\Users\harsh\Downloads\reactabular-master\reactabular-master>npm install
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.5 should be installed with -g

> git-validate@2.1.4 install C:\Users\harsh\Downloads\reactabular-master\reactabular-master\node_modules\git-validate
> node bin/install

WARNING: Unable to find a .git directory for this project, installation aborted.

> phantomjs-prebuilt@2.1.8 install C:\Users\harsh\Downloads\reactabular-master\reactabular-master\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\harsh\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...
  [========================================] 100%
Received 17767K total.
Extracting zip contents
Removing C:\Users\harsh\Downloads\reactabular-master\reactabular-master\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\harsh\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1469697024957\phantomjs-2.1.1-windows -> C:\Users\harsh\Downloads\reactabular-master\reactabular-master\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\harsh\Downloads\reactabular-master\reactabular-master\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> git-prepush-hook@1.0.1 install C:\Users\harsh\Downloads\reactabular-master\reactabular-master\node_modules\git-prepush-hook
> node bin/install

> radium@0.18.1 postinstall C:\Users\harsh\Downloads\reactabular-master\reactabular-master\node_modules\radium
> cd lib || npm run lib

> reactabular-monorepo@1.0.0 postinstall C:\Users\harsh\Downloads\reactabular-master\reactabular-master
> node lib/post_install.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! reactabular-monorepo@1.0.0 postinstall: `node lib/post_install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactabular-monorepo@1.0.0 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactabular-monorepo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactabular-monorepo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactabular-monorepo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\harsh\Downloads\reactabular-master\reactabular-master\npm-debug.log

C:\Users\harsh\Downloads\reactabular-master\reactabular-master>

please help me to solve this problem

**Comment by bebraw** [comment]
@venkirocking2 I removed that `postinstall` bit. Could you give it a go now?

**Comment by venkirocking2** [comment]
Now i am gettting this issue local host is getting loaded but it was blank....:(

C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master>npm start

> reactabular-monorepo@1.0.0 start C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master
> webpack-dev-server

http://localhost:8080/
webpack result is served from /
content is served from C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master
404s will fallback to /index.html

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/paginating.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/paginating.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/installing.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/installing.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./CONTRIBUTING.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./CONTRIBUTING.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./CONTRIBUTORS.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./CONTRIBUTORS.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./LICENSE.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./LICENSE.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/table/introduction.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\table
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/table/introduction.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/table/styling.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\table
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/table/styling.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/table/overriding-default-elements.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\table
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/table/overriding-default-elements.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/introduction.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\column-definition
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/introduction.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/props.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\column-definition
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/props.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/header.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\column-definition
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/header.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/cell.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\column-definition
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/cell.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/formatters.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\column-definition
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/formatters.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/transforms.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\column-definition
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/transforms.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/nested-columns.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\column-definition
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/column-definition/nested-columns.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/all-features.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/all-features.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/crud.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/crud.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/drag-and-drop.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/drag-and-drop.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/excel.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/excel.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/fixed-width-columns.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/fixed-width-columns.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/infinite-scrolling.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/infinite-scrolling.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/selection.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/selection.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/sort-and-search.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/sort-and-search.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/toggle-columns.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/toggle-columns.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/tree-view.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\docs\examples
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./docs/examples/tree-view.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-table/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-table
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-table/README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-resolve/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-resolve
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-resolve/README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-sort/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-sort
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-sort/README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-sticky/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-sticky
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-sticky/README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-easy/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-easy
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-easy/README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular/CHANGELOG.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular/CHANGELOG.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-edit/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-edit
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-edit/README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-search/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-search
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-search/README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-highlight/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-highlight
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-highlight/README.md 3:23-152

ERROR in ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-resizable/README.md
eactabular-master (1)or: Cannot resolve module 'C:UsersharshDesktop
ode_modulescataloglibcomponentsPagePageRenderer' in C:\Users\harsh\Desktop\reactabular-master (1)\reactabular-master\packages\reactabular-resizable
 @ ./~/catalog/lib/loader.js!./~/raw-loader!./packages/reactabular-resizable/README.md 3:23-152
Child html-webpack-plugin for "index.html":


![image](https://cloud.githubusercontent.com/assets/20697143/17239345/01b46530-5581-11e6-9c32-25e10fef0cbd.png)

**Comment by bebraw** [comment]
This feels like a path issue.

Could you try running [Catalog](https://github.com/interactivethings/catalog)? If that fails, then it's something at Catalog, else it's something for me to figure out. 👍

**Comment by bebraw** [comment]
@venkirocking2 Any luck with this?

**Comment by bebraw** [comment]
I think I'll close this for now. Feel free to open again if you encounter this again. The project has changed quite a bit since the report and I'll likely ditch Catalog at some point after my own tooling has reached a good enough level.
