### ISSUE TITLE
Possibility to focus editor on activation

### ISSUE THREAD

**Issue by apsavin** [reactabular/reactabular#180]
Hi!
Thanks for the great library!

I have a little problem with it. When user activates an editor (for example, `input` built-in editor), the editor is not focused. So, if user wants to start editing (or even if it was a misclick and user wants just to leave the edit mode), user must to focus the input and then to blur it. It's not very handy.

Can I force input to appear focused somehow? If no, what about implementation of such a feature? Can it be on the roadmap? Maybe, it's better not to use built-in editors if I want such a feature?

**Comment by bebraw** [comment]
Hi,

> I have a little problem with it. When user activates an editor (for example, input built-in editor), the editor is not focused. So, if user wants to start editing (or even if it was a misclick and user wants just to leave the edit mode), user must to focus the input and then to blur it. It's not very handy.

That's a valid point. I wonder if that would be a good default behavior even. As far as I can see, we could achieve that through a ref. Something along `ref={e => e && e.focus()}` would likely work.

If you want to give it a quick go, implement a custom version of [edit](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-edit/src/edit.js). It's that `children` bit that's crucial. It should return something that does the trick above. This means you'll have to use either a class based component or `React.createClass` to manage the ref. I wouldn't mind a PR on this and I can take a good look at this myself at a later time so let's leave this open for now.

Now that I think of it, maybe it should be possible to inject what `children` returns. We could maintain backwards compatibility this way. That focus idea would go to something we would pass as a parameter. But this is something I can think about and implement as well.

I'll most likely push the edit component out of this project (#176) so it's easier to expand. There's nothing Reactabular specific there and it would be useful in other contexts as well.

**Comment by bebraw** [comment]
I figured out an easy fix for this.

When you are initializing something like `edit.input`, you can do (`edit.input({ autoFocus: true })`). That enables the behavior you want without having to tweak Reactabular. 👍

**Comment by apsavin** [comment]
@bebraw thank you very much!

A little fix: `edit.input({ props:{autoFocus: true} })`.

So, reactabular can just set this prop by default. Possibility to set custom props already exists, so users of the library will be able to redefine this behavior.

**Comment by bebraw** [comment]
I think I'll make that the default setting in `2.0`. I'll separate the editing portion from the main project and close this issue then.

Thanks for bringing this to my attention. 👍
