### ISSUE TITLE
autoExpandColumn

### ISSUE THREAD

**Issue by venelin-mihaylov** [reactabular/reactabular#186]
Hi there,
  I need the table to expand within its container, and I need one of the columns to take up the space that is not explicitly allocated to the others (there is such feature on ExtJS, I come from there, it's a nice one ;) )
 So, I guess that the way to go about that is to recalc the column width on every table update, and then set it via refs? Is that right? I would appreciate a tip how to implement that...
 Also, if I want to set column width in percentage, would the same approach be OK?

 Example 1:
```
{
  column1:  {width: 100},
  column2: {
     autoExpand: true
  }
}
```

 Example 2:
 ```
{
  column1:  {width: '10%},
  column2: {
     width: '90%',
  }
}
```

How big would the performance penalty for such a feature?
 Thanks in advance :)

**Comment by bebraw** [comment]
Hi,

I think we can pull this off through CSS. You could set something like

```
[
  {
    props: {
      style: {
        width: '100%'
      }
    },
    ...
  },
  ...
]
```

That will propagate to both header and body cells. An alternative would be to set a `className` for a header cell and then control that through a separate CSS definition.

I think I'll write a little demo for this.

**Comment by venelin-mihaylov** [comment]
A demo would be fantastic, thank you.

**Comment by venelin-mihaylov** [comment]
Hehe, didn't know calc(), great! :)

**Comment by bebraw** [comment]
The only problem with `calc()` is that now you have an implicit dependency. It will get trickier as you add more columns to the system. That said, it would be possible to push that calculation to React with a little helper.

**Comment by venelin-mihaylov** [comment]
For my use case, straight calc() will be enough (I hope). 
I can see that if an option to resize/move/hide columns is present, then calc() will have to be managed by react ...
