### ISSUE TITLE
publish error - reactabular-table/src/body.js is out dated

### ISSUE THREAD

**Issue by bear2029** [reactabular/reactabular#190]
Just installed 1.2.6 and found this issue, after some reverse engineering, realized this file is dated and cause `property` attr is still needed under `column.cell`

Here is the critical area in `reactabular-table/src/body.js`:

```javascript
  render() {
    const { columns, components, row, rowProps, rowIndex, rowData } = this.props;

    return React.createElement(
      components.row,
      rowProps,
      resolveBodyColumns(columns).map(({ column, cell, props }, j) => {
        const {
          property,
          transforms = [],
          format = a => a
        } = cell;
```

Your [latest version](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-table/src/body.js#L88) from repo looks correct but the actual code in npm didn't seems to be published properly.

**Comment by bebraw** [comment]
Yeah, the repository readme represents development state. You can find the correct one [here](https://www.npmjs.com/package/reactabular-table) and at the [official site](http://reactabular.js.org/).

I'll be doing that change in 2.0. My goal is to get a release out there today.

**Comment by bebraw** [comment]
Pushed 2.0 so closing.
