### ISSUE TITLE
select does not work with 2.0.2

### ISSUE THREAD

**Issue by venelin-mihaylov** [reactabular/reactabular#191]
Hi there,
  I upgraded to 2.0.2
  After the upgrade selecting rows stopped working.
  More specifically -reactabular table is *not* re-rendered when the selected row state is changed. If the component is unmounted/mounted, the new state is properly rendered - the new selection marked. 

  Downgraded to 1.2.6 - working, Upgraded to 2.0.2 again, does not work.
  I have a "BaseTable" component which is a facade for the reactabular table in my app. 
  I use redux for state.

```
import React from 'react'
import {Table, select} from 'reactabular'
import {autobind} from 'core-decorators'
import {mergeClassNames} from 'reactabular-utils'
import findIndex from 'lodash/findIndex'
import noop from 'lodash/noop'

import styles from 'styles/components/BaseTable.css'

@autobind
export default class BaseTable extends React.Component {

  static propTypes = {
    columns: React.PropTypes.any,
    rows: React.PropTypes.any,
    rowKey: React.PropTypes.any,
    onSelectRow: React.PropTypes.func,
    onRow: React.PropTypes.func,
    selectedRowId: React.PropTypes.any,
    selectedRowIdField: React.PropTypes.string,
  }

  static defaultProps = {
    onRow: () => ({}),
    onSelectRow: noop,
    selectedRowIdField: 'id',
  }

  onRow(row, rowIndex) {
    const {
      selectedRowId,
      selectedRowIdField,
      onRow,

    } = this.props
    const {className, ...props} = onRow(row, rowIndex)
    const selected = row[selectedRowIdField] === selectedRowId
    return {
      className: mergeClassNames(className, selected && styles.selectedRow),
      selected,
      onClick: () => this.selectRow(rowIndex),
      ...props,
    }
  }

  selectRow(selectedRowIndex) {
    const {selectedRowIdField, rows} = this.props

    const selected = select.row({
      rows,
      selectedRowId: rows[selectedRowIndex][selectedRowIdField],
    })

    this.props.onSelectRow({
      selectedRowId: selected.selectedRow[selectedRowIdField],
      selectedRow: selected.selectedRow,
    })
  }

  render() {
    const {
      columns,
      rows,
      rowKey,
      onRow, // eslint-disable-line
      onSelectRow, // eslint-disable-line
      selectedRowId,
      ...rest,
    } = this.props // eslint-disable-line no-unused-vars

    const selectedRowIndex = findIndex(rows, {[rowKey]: selectedRowId})
    return select.byArrowKeys({
      rows,
      selectedRowIndex,
      onSelectRow: this.selectRow,
    })(<Table.Provider
      className='pure-table pure-table-striped'
      columns={columns}
      style={{
        width: '100%',
      }}
    >
      <Table.Header />

      <Table.Body
        onRow={this.onRow}
        {...{rows, rowKey}}
        {...rest}
      />
    </Table.Provider>)
  }
}
```

Thank you

**Comment by bebraw** [comment]
Can you set up a standalone project to study? It might be easiest to fork this repository and set up an example.

**Comment by bebraw** [comment]
Selection state should go to the rows structure by the way. Otherwise Reactabular can't tell that a refresh is needed. That could be it.

**Comment by venelin-mihaylov** [comment]
I created a esnextbin gist: https://esnextb.in/?gist=481f0990801407fa58f02815ee5081f7
I set it up with 1.2.6, and even then the rows are not re-rendered. I guess I am going something wrong, but can't find what :(

**Comment by bebraw** [comment]
The problem at Gist is that the change doesn't alter the row data. It needs to change the row data for Reactabular to know which rows to re-render. This is why my [example](http://reactabular.js.org/#/selecting-rows) picks up `select.row` result and uses it to update the row state.

**Comment by venelin-mihaylov** [comment]
Right, thanks, will update my code. Thank you for your time.

**Comment by venelin-mihaylov** [comment]
Hi there,
  I got it working.
  Maybe it it would be appropriate to be explicitly mentioned that "rows" is being mutated by the select HOC. For me that part wasn't clear (and I didn't pay enough attention to the example) and that led to my mistake.

**Comment by bebraw** [comment]
Yeah, I'll add a note about that. Good point.
