### ISSUE TITLE
Transforms documentation

### ISSUE THREAD

**Issue by tomhelmer** [reactabular/reactabular#192]
I wan't to make a cell transforms adding a onClick handler to the cell.

Something like : 

`transforms: [label => ({ onClick: this.cellClick }) ]`

..but I can't figure out if I can pass the extra celldata to this handler

**Comment by bebraw** [comment]
Hi,

See the [full definition](http://reactabular.js.org/#/column-definition/transforms). Basically you get

```javascript
cell.transforms = [(<value>, { columnIndex: <number>, column: <object>, rowData: <object>, rowIndex: <number>, property: <string> })
```

What sort of data do you need to pass there? It might be convenient to pass it through `rowData`.

**Comment by tomhelmer** [comment]
I wan't to pass a property from rowData to my this.cellClick function, but can't figure out if it's possible.

**Comment by bebraw** [comment]
Alright. Then you could try something like this:

```javascript
transforms: [(label, { rowData }) => ({
  onClick: () => this.cellClick(rowData.id)
) ]
```

After this change it would pass `id` from `rowData` to `this.cellClick`.

**Comment by tomhelmer** [comment]
Thanks, it works like a charm

There was a missing bracket :

```
transforms: [(label, { rowData }) => ({
  onClick: () => this.cellClick(rowData.id)
}) ]
```

**Comment by bebraw** [comment]
Cool. Let's close this then. 👍
