### ISSUE TITLE
Error in docs/all-features

### ISSUE THREAD

**Issue by sovetkin-am** [reactabular/reactabular#196]
I copy code with http://reactabular.js.org/#/examples/all-features and with https://github.com/reactabular/reactabular/tree/master/docs

And get the error in 

`import {
  Table, search, edit, sort, highlight, resolve,
  SearchColumns, resizableColumn
} from 'reactabular';`

Because a component is `edit` not found

Perhaps it should be replaced by
```
import {
 Table, search, sort, highlight, resolve,
 SearchColumns, resizableColumn
 } from 'reactabular';
import * as edit from 'react-edit'
```

**Comment by bebraw** [comment]
Yeah. Good catch! I'll get that fixed in a bit. 👍

**Comment by bebraw** [comment]
Should be fixed now. Thanks!
