### ISSUE TITLE
Redux Example

### ISSUE THREAD

**Issue by jmatsushita** [reactabular/reactabular#198]
Hi there,

It would be great to have an example of Reactabular used with Redux. I'm struggling to understand how props and state are supposed to interact and the breadcrumb `// this could go through flux etc.` in the [CRUD example docs](http://reactabular.js.org/#/examples/crud) isn't enought to get me going.

In particular I'm thinking that props should be driving the rows data and that the `this.state` should be reserved to the component's sorting and filtering state (for instance).

Hope this might be useful to others!

Jun

**Comment by bebraw** [comment]
Good point. In part it depends on what you want to maintain at Redux. It would be possible to push entire table state there. But, yeah, example would clear this up.
