### ISSUE TITLE
Example on how to pass rowData to Editable component

### ISSUE THREAD

**Issue by jmatsushita** [reactabular/reactabular#200]
Hi again,

I love the functional style of the component by the way. I'm not sure whether this doesn't break something else since I'm a bit green with React but I find that replacing [this section in `react-edit/src/edit.js`](https://github.com/reactabular/reactabular/blob/master/packages/react-edit/src/edit.js#L31-L41) and adding `extraParameters`

```
        children: React.createElement(
          editorComponent,
          {
            ...props,
            extraParameters,
            [editingProps.value || 'value']: getEditedValue(value),
            [editingProps.onValue || 'onValue']: v => onValue(
              { value: v, ...extraParameters }
            )
          }
        )
```

allows me to then access `rowData` in the following way for editable components that depend on value in another column:

```
const myInput = ({ props } = {}) => {
  const Input = ({ value, onValue, extraParameters }) => {
```

Is there a better way to do this? (I got a bit lost without types to guide me with `transforms`, `editable` and a custom `react-edit` component :) )

Cheers,

Jun

**Comment by bebraw** [comment]
That seems like a worthwhile addition. Backwards compatible as well. Do you want to PR?

**Comment by jmatsushita** [comment]
Great! Let me know if the PR works!
