### ISSUE TITLE
Resize handle not available

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#202]
I am trying the full demo in my react application. The resize handle is not available. I copied over some styles related to sorting. Are there more styles which need to be copied over? If so, appreciate if the documentation is updated with it.

**Comment by bebraw** [comment]
@vijayst I have suggested styling [here](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-resizable/style.css). I'll add a mention to the readme. Thanks.
