### ISSUE TITLE
Allow rowTitle and rowParent options for trees

### ISSUE THREAD

**Issue by jmatsushita** [reactabular/reactabular#203]
Hi there!

Thanks for adding me as a contributor :)

Here's another feature request: it would be nice to be able to allow `reactabular-tree` to keep counting it's chickens with an `id` and `parent` key, but to make this configurable so that you can for instance hide the `id` key and instead display the toggle icon on a `rowTitle` column, as well as specify a different name for the `parent` key.

What do you think?

Jun

**Comment by bebraw** [comment]
Yeah, that would work for me. PRs would be definitely welcome. Do those separately so `parent` renaming and the rest go to their own.

**Comment by bebraw** [comment]
Just realized you can set `id` and `parent` already in the current functions. Check out the current code. Feel free to point out problematic bits. 👍

**Comment by bebraw** [comment]
I revised the API for 6.0 (not out yet). You can see the idea [here](https://github.com/reactabular/reactabular/tree/master/packages/reactabular-tree). It should be possible to customize the fields now. I can add more hooks as needed (more flexible now).
