### ISSUE TITLE
Removing column from the table does not clear associated filter.

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#205]
I use the following code  to remove / toggle columns.

```
handleToggleColumn(property) {
    let { query } = this.state;
    const columns = cloneDeep(this.state.columns);
    const column = columns.find(col => col.property === property);
    column.visible = !column.visible;
    if (!column.visible) {
      // make sure the filter is cleared
      query = omit(query, [column.property]);
    }
    this.setState({ columns, query });
  }
```

On removing the column, I am using lodash omit to remove the associated property from the query. But still, the filter value is showing in the next column.

Filter on "Computer name" column.
![screen shot 2016-09-22 at 2 53 09 pm](https://cloud.githubusercontent.com/assets/3457565/18742991/98467f5a-80d4-11e6-9b1c-080c9311fccd.png)

On removing computer name column, the filter shows in the next column, "Manufacturer"
![screen shot 2016-09-22 at 2 53 34 pm](https://cloud.githubusercontent.com/assets/3457565/18742999/9e5723a4-80d4-11e6-961a-fdeee9e34482.png)

The same issue can also be seen in the full demo.

**Comment by bebraw** [comment]
Good catch. Missing filtering somewhere. I'll fix the demo at least. Thanks!

**Comment by vijayst** [comment]
Thanks @bebraw. Can I work on this and create a PR?

**Comment by bebraw** [comment]
@vijayst Yeah, PR would be cool. 👍
