### ISSUE TITLE
Selecting a row should add a CSS class to the row

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#206]
Selecting a row should add a CSS class to the row. The class added should be something like "select-row". The select-row should use a different default color other than odd-row and even-row.

**Comment by vijayst** [comment]
I got this done through some workaround code like this:
```
handleSelectRow(row, rowIndex) {
    if (this.selectedRow) {
      const prevSelector = `table.${this.props.className} tbody tr:nth-child(${this.selectedRow})`;
      const prevNode = document.querySelector(prevSelector);
      prevNode.className = this.selectedRow % 2 ? 'even-row' : 'odd-row';
    }
    const selector = `table.${this.props.className} tbody tr:nth-child(${rowIndex + 1})`;
    const node = document.querySelector(selector);
    node.className = 'select-row';
    this.selectedRow = rowIndex + 1;
    this.props.onSelectRow(row);
  }
```

Preferably, odd-row, even-row, select-row classes should be part of reactabular render.

**Comment by bebraw** [comment]
Check the `onRow` part [here](https://github.com/reactabular/reactabular/tree/master/packages/reactabular-select). I do a check like `row.selected && 'selected-row'` there. The class related logic lives outside.

What you suggested can work, but it's likely neater to go through `onRow`.

**Comment by vijayst** [comment]
Thanks for sharing the select api. Having the classnames in the onRow does not work for me. Whenever the state changes and there is a re-render, the onRow is not called. I think onRow is called only for new rows or rows with new keys. Because the onRow is **NOT** called, the selected row does not get the class.

**Comment by bebraw** [comment]
The underlying logic expects the selection state lives at row level. If it's separate, the rendering logic won't be able to detect the change by default. That could explain it.

I could make it possible to override the current `shouldComponentUpdate`. There's a flag to disable it, but maybe there's a better way.

**Comment by vijayst** [comment]
The select api works fine. The code should not use rowIndex but use the row.id as follows:
```
handleRowEvent(row, { rowIndex }) {
    return {
      className: row.selected && 'select-row',
      onClick: () => this.handleSelectRow(row)
    };
  }

  handleSelectRow(row) {
    this.setState({ selectedRowId: row.id });
    this.props.onSelectRow(row);
  }
```
