### ISSUE TITLE
Horizontal scrollbar if the table size exceeds the screen width.

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#207]
react-pagify uses a horizontal scrollbar when the size of the widget is larger than the screen width.
![screen shot 2016-09-23 at 11 11 42 am](https://cloud.githubusercontent.com/assets/3457565/18775351/9038e88e-817e-11e6-927b-99b204086320.png)

A similar horizontal scrollbar is required for the main table when the table size exceeds the screen width. The screenshot below shows how the table appears cut off with no indication to scroll to the right.
![screen shot 2016-09-23 at 11 07 06 am](https://cloud.githubusercontent.com/assets/3457565/18775312/58319e86-817e-11e6-92b3-b48083326b60.png)

**Comment by git-toni** [comment]
If I'm not mistaken, Reactabular is in general strongly *non*-opinionated with regard to styling; hence what you ask is not provided.
Do you have a jsbin/codepen to show the behaviour? 

I would suggest to try adding `overflow-x:auto;` to your Reactable's parent container 's CSS.
E.g.
```javascript
<div id='mytable'>
  <Table.Provider ...>
    ...
  </Table.Provider>
</div>
```
```scss
div#mytable{
  overflow-x: auto; // alternatively use "scroll" instead of auto
}
```

**Comment by vijayst** [comment]
Thanks @git-toni. overflow-x: auto to the container is what I needed. It worked.
