### ISSUE TITLE
Documentation woes for easy example

### ISSUE THREAD

**Issue by joeyfigaro** [reactabular/reactabular#209]
[Example Source](http://reactabular.js.org/#/easy)

Currently running into a few issues attempting to build a searchable table with sortable headers: 

- Example assumes drag and drop is desired. It's not in my case. 
- Example uses two helpers for generating rows/parents without including the source of the helpers.
- As a result of using helpers, the generated rows that are provided to `<EasyTable />` are not available. What do they look like? 

## current errors
`reactabular-virtualized`:

complaining about `forceUpdate()` being used on an unmounted component: `warning.js?8a56:36Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the VirtualizedBody component.`

**Comment by bebraw** [comment]
I would need to see some code to say what might be causing the error.

**Comment by joeyfigaro** [comment]
@bebraw Thank you! Give this guy a shot: [https://gist.github.com/joeyfigaro/d3606b46d720a5135afde8d54b0dab44](https://gist.github.com/joeyfigaro/d3606b46d720a5135afde8d54b0dab44)

**error:**
![](https://d3vv6lp55qjaqc.cloudfront.net/items/07212q3i3Y3t3M1F3b2y/Image%202016-09-28%20at%2011.44.08%20AM.png?X-CloudApp-Visitor-Id=a9ed7181fccb55820cf8657707cbf00a&v=f3c4bdd2)
