### ISSUE TITLE
Allow searching in arrays

### ISSUE THREAD

**Issue by mathieumg** [reactabular/reactabular#211]
Discussion started in https://gitter.im/reactabular/reactabular?at=57ee9a024380866f04cb1cbf

To summarize, currently `reactabular-search` only expects to deal with strings, but in an effort to accommodate as many use cases as possible, it will try to cast a column's value to string. This works well most of the time: a number such as `1337` would become the searchable string `"1337"` following that logic. However, when dealing with an array, such as `["Black", "White", "Blue"]`, it gets casted to `"Black,White,Blue"`. Again, that is "fine" if you just wanted to give search a hand, but it starts to introduce issues. Notably, the query `,` now returns every row that has at least an item in that array as a result. It also becomes much more difficult to handle the search highlights since they are computed against once string, but the original data is still an array that could be mapped to an unordered list, for example.

So currently `search.multipleColumns` populates `_highlights` as such for the `Bl` query:

```js
{
  _highlights: {
    colors: [
      {
        startIndex: 0,
        length: 2,
      },
      {
        startIndex: 12,
        length: 2,
      },
    ],
  },
  name: "colors",
},
```

The idea would be for it to traverse arrays and run the search against sub-items:

```js
{
  _highlights: {
    colors: [
      [{
        startIndex: 0,
        length: 2,
      }],
      ,
      [{
        startIndex: 0,
        length: 2,
      }],
    ],
  },
  name: "colors",
},
```

As you can realize, it keeps the indexes aligned in the results by using sparse arrays. Then, the formatting code could look something like that for the `colors` column:

```js
cell: {
  format: (colorList, {rowData: {_highlights: {colors}}}) => (
    <ul>
      {colorList.map((colorName, index) => (
        <li key={index}>
          {highlight.cell(colorName, colors[index])}
        </li>
      ))}
    </ul>
  ),
},
```

I'm presuming `highlight.cell(colorName, undefined)` just maps to `colorName` but I didn't double check. It isn't the case here, but the approach would be the same for any level of nesting with arrays. There is also the case of objects I didn't explore, but it could potentially be considered as well.

**Comment by bebraw** [comment]
Your specification looks good to me. The core logic won't change but you'll get extra logic against arrays.

Do you want to give it a go? Search and highlighting in particular have been peppered with tests so it should be fairly nice to expand.

**Comment by mathieumg** [comment]
> Do you want to give it a go?

Yep, I'll look into it. Shouldn't be a problem.

**Comment by mathieumg** [comment]
I'm looking into implementing this and I have a few design questions. Currently, the line that "does too much" is https://github.com/reactabular/reactabular/blob/fa866c89fad185affcd38f7433c4af862e5db9f4/packages/reactabular-search/src/_column_matches.js#L12

That cast to a string is forced down our throat. I see a few ways around that. One of them is:

```js
const resolvedValue = row[`_${property}`] || String(row[property]);
```

Which means, if there is a special resolved value, we expect our strategy to be able to handle it, knowing that it might not always be a string. Another would be a configurable casting strategy:

```js
const _columnMatches = ({
  // ...
  castingStrategy = v => String(v)
}) => {
  // ...
  const resolvedValue = castingStrategy(row[`_${property}`] || row[property]);
```

Finally, we could just hardcode a special case as we discussed:

```js
const resolvedRawValue = row[`_${property}`] || row[property];
const resolvedValue = Array.isArray(resolvedRawValue) ? resolvedRawValue : String(resolvedRawValue);
```

What are your two cents? :)

**Comment by bebraw** [comment]
Maybe it would be possible to combine

```javascript
const resolvedRawValue = row[`_${property}`] || row[property];
const resolvedValue = Array.isArray(resolvedRawValue) ? resolvedRawValue : String(resolvedRawValue);
```

with optional casting strategy. This would give us nice behavior out of the box while allowing extension for more exotic use cases that go beyond the defaults.

**Comment by mathieumg** [comment]
So this modification would become:

```js
const _columnMatches = ({
  // ...
  castingStrategy = v => Array.isArray(v) ? v : String(v),
}) => {
  // ...
  const resolvedRawValue = row[`_${property}`] || row[property];
  const resolvedValue = castingStrategy(row[`_${property}`] || row[property]);
```

Plus of course the appropriate logic to handle this array in the search strategies.

**Comment by bebraw** [comment]
Yeah, looks good to me.
