### ISSUE TITLE
Need more documentation on how to do a work with package install from GitHub repo.

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#215]
I forked the repo. I installed reactabular using 
`npm install --save https://github.com/vijayst/reactabular.git`

The package.json shows a different package name:
`"reactabular-monorepo": "git+https://github.com/vijayst/reactabular.git"`

I am trying to import Table as I normally do with reactabular. All of the below are throwing an error:

```
import Table from 'reactabular';
import Table from 'reactabular-monorepo';
import Table from 'reactabular-monorepo/packages/reactabular';
```

I browsed the package.json and I found the main is pointing to dist. Is this way of working with reactabular via git repo not encouraged?

**Comment by bebraw** [comment]
This might be a little hard to solve since the project relies on a monorepo. Effectively the root level `package.json` is used to manage the related tooling and I don't expect it to work neatly out of the box.

That said, I will ask around to see if people have solved this in their projects.

**Comment by bebraw** [comment]
I did a couple of tweaks related to this. If I did it right, you should be able to set `"reactabular": : "git+https://github.com/vijayst/reactabular.git"`. There's a `postinstall` script that bootstraps lerna and builds the projects.

The gotcha is that `react-edit` isn't included in the build. The same goes for the secondary packages. These should be extracted to project of their own anyhow so maybe we'll end up with a repo for `react-edit` and `reactabular-extra` or so.

I haven't given it a go (just did the config). If you do, let me know how it goes.

**Comment by vijayst** [comment]
Thanks @bebraw. I got an error that ./src folder was not found. I also had to install lerna globally to get it work.

**Comment by bebraw** [comment]
@vijayst Ah, I just did a little tweak related to that. It has to run `npm install` at the `postinstall` script.

There's still a glitch around, though. I run the build process through `lerna run build`. This in turn causes the root level `postinstall` to run for after each package has been built. That doesn't look particularly nice. I have to see if there's some nice way to get around that.

**Comment by bebraw** [comment]
By the looks of it `lerna bootstrap` runs `npm prepublish` for each package so that will simplify things a notch!

**Comment by vijayst** [comment]
I tried npm install. It goes on an infinite loop, doing something repeatedly.
> reactabular@1.0.0 postinstall /Users/vijayst/Documents/react/sam/reactabular-filter-demo/node_modules/reactabular
> npm install && lerna bootstrap

**Comment by bebraw** [comment]
Yeah, I'm currently working on this. I have a rough idea how to work around that. 👍

**Comment by bebraw** [comment]
@vijayst I set up a separate Node script for handling this case. It still fails with `Error: Command failed: npm run bootstrap`. Now the issue might be something more debuggable (feels path related).

**Comment by vijayst** [comment]
ok great, thanks @bebraw

**Comment by bebraw** [comment]
Here's a trace about what happens right now if you try to `npm install` through Git:

```bash
> reactabular@1.0.0 bootstrap .../node_modules/reactabular
> lerna bootstrap

Lerna v2.0.0-beta.30
`packages/` directory does not exist, have you run `lerna init`?
```

So it definitely feels like something path related. As far as I understand, `packages` directory should exist there since it's in the Git repository.

Here's the core part of what happens on post install:

```javascript
stat('node_modules/lerna', function(error, stat) {
  // Skip building on Travis
  if (process.env.TRAVIS) {
    return;
  }

  if (error || !stat.isDirectory()) {
    exec('npm i lerna@2.0.0-beta.30');
    exec('lerna bootstrap'); // tried also npm run bootstrap since that would patch env
  }
});
```

Given it doesn't install development dependencies when a package is installed (totally logical), I install Lerna first. After that I run Lerna, but that's also where I go wrong somehow. Most likely I'm missing something small detail right there.

**Comment by vijayst** [comment]
@bebraw I have not worked with lerna before. It requires `lerna init`if it cannot find lerna.json. lerna.json should be part of the download.

**Comment by bebraw** [comment]
Yeah, `lerna.json` should definitely be there. I have to dig deeper to understand how pointing to Git with npm is supposed to work exactly.

**Comment by vijayst** [comment]
lerna.json may be required to be explicitly set within files property of package.json.
```
files: [
  'lerna.json'
]
```

**Comment by bebraw** [comment]
Ah, I'll give that a go. Thanks for the tip.

**Comment by bebraw** [comment]
I set up `files` (same error). Still missing something painfully obvious.

**Comment by vijayst** [comment]
I spent some time on this. A good way to make it work or trouble-shoot is:
1. Comment out the npm run bootstrap from post-install.
2. Use npm i <github-url> in a sample project.
3. Go to the node_modules/reactabular folder and run `lerna bootstrap` and get it to work. 

I modified files to include `packages/**/*`. But, it keeps throwing ./src not found!

**Comment by bebraw** [comment]
Ah, maybe it's trying to run `lerna bootstrap` at the project root instead of the package root. Perhaps we can patch the post-install script so that it sets the working directory right. I'll give that a go.

**Comment by bebraw** [comment]
The `cd` trick won't work. There has to be some other way.

**Comment by bebraw** [comment]
Looks like [jest](https://github.com/facebook/jest) has a setup of its own. That might be worth replicating. They bootstrap as well but a little differently.

**Comment by bebraw** [comment]
Given I split up the project and there's no `reactabular` wrapper, it might be interesting to revisit this.

**Comment by bebraw** [comment]
@vijayst What do you want to do with this? Time to close?

**Comment by vijayst** [comment]
Yes, please close it. The new split structure is easy to work with.
