### ISSUE TITLE
Date filter for date fields.

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#218]
I need a date filter for date fields in reactabular grid. The date filter should have:
1. Start date.
2. End date.
3. Filter Button.
4. Clear Button.

The date filter should work as follows:
1. If Start date is provided, all dates after start date is filtered.
2. If End date is provided, all dates before end date is filtered.
3. If both Start date and End date are provided, all dates between start date and end date is filtered.
4. Filter should work only on clicking Filter button.
5. Clear button should remove the date filters.

**Comment by bebraw** [comment]
That would make a great package. I think you can keep it in vanilla React as long as you follow the interface Reactabular expects. Depending on the browsers you want to support, you might be able to leverage native elements for this purpose.

Assuming this plugs into `reactabular-search-columns` we'll need to expand that to support custom fields per column.

**Comment by vijayst** [comment]
[react-dates](https://github.com/airbnb/react-dates) has a good date picker that can be leveraged. I prefer the SingleDatePicker of react-dates.

**Comment by bebraw** [comment]
@vijayst Safe to close? Did you figure it out?

**Comment by vijayst** [comment]
@bebraw I will have to work on this one, most likely on January :). Please feel free to close it. I will update the issue with a comment when done. Thanks.

**Comment by bebraw** [comment]
Cool. Thanks.

**Comment by vijayst** [comment]
I published an opinionated package - [searchtabular-antd](https://www.npmjs.com/package/searchtabular-antd). The package makes use of antd to add date filter, range filter (for numbers) and checkbox filter (for boolean).

**Comment by bebraw** [comment]
Nice! Please make a doc PR to `searchtabular` so people find yours.

**Comment by vijayst** [comment]
I have already forked once for searchtabular-antd and updated the ReadMe.
It does not let me fork again to create a PR.

**Comment by bebraw** [comment]
No probs. I added a mention. 👍

**Comment by vijayst** [comment]
Thanks
