### ISSUE TITLE
import findIndex from lodash

### ISSUE THREAD

**Issue by BenGosub** [reactabular/reactabular#219]
In the example code for reactabular-easy you define `onRemove` function as:

`  onRemove(id) {
    const rows = cloneDeep(this.state.rows);
    const idx = findIndex(rows, { id });

    // this could go through flux etc.
    rows.splice(idx, 1);

    this.setState({ rows });
  }`

And an error is raised because findIndex is not defined. Looking from the other examples this is a Lodash function that needs to be implemented.
Great project btw, really looking forward to using it in my projects.

Regards,
Bozhidar

**Comment by bebraw** [comment]
Thanks! Fixed. It's easy to miss those as the example imports aren't being linted.
