### ISSUE TITLE
Allow `cell.transformations` row-wise or even cell-wise, not just column-wise

### ISSUE THREAD

**Issue by git-toni** [reactabular/reactabular#223]
I've been trying to use Reactabular in some cases where each row does *not* contain the same "family" of item. Eg.
```
---------------------------------------------
Total price ||   1000$ (no edit)
---------------------------------------------
Country     ||    US(edit-dropdown)
---------------------------------------------
Discount    ||   12%  (edit-input)
---------------------------------------------
```

As you can see, each row of the second column requires a different transformation (none, edit-dropdown, edit-input). Hence the transformation is variable *cell-wise*.

So some extra cases one can imagine:

- Given a `.selected=true` row => make each(or some) of its cells editable, in contrast to the other rows
- As in the example above, have the option to conditionally transform a single cell, given some of its properties/label/name.
- *Extra*(a bit out of scope): If the above were implemented, a nice side-effect would be to allow transposing columns for rows when displaying data, ie. each item would live on a column, and the header would be the first column.

Some of these features would require rather fundamental changes in the library, so I'm just raising the topic here for discussion. :D
Ofc another fine option is to agree that Reactabular is not intended to provide so many features/flexibility  for the sake of maintanability/stability and stick to the current more opinionated form of table.

**Comment by bebraw** [comment]
Maybe it would be possible to achieve this on top of the current architecture. I imagine you could check against some data at the `cell.transforms` handler and then attach logic based on that. This would be far more complicated than the default case, but it just might do the trick. I'm thinking something like this:

```javascript
{
  cell: {
    transforms: [
      edit.branch({
        country: editable(edit.dropdown()),
        discount: editable(edit.input())
      })
    ]
  }
}
```

`edit.branch` would do the check. You may need to extend the idea a bit to make it work for you.

**Comment by git-toni** [comment]
Interesting! Such a switch/mapping approach could definetely work. And probably adding another transform aware of the current rows could work for case 1 too. I will give it a try whenever I have the need again(ended up with a work-around)/some time.

**Comment by bebraw** [comment]
Cool. Let me know how it goes. `edit.branch` would be a good addition to the core I think.
