### ISSUE TITLE
Not compatible with lodash 3

### ISSUE THREAD

**Issue by apsavin** [reactabular/reactabular#226]
[Such](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-table/src/body.js#L1) import of functions from `lodash` is not compatible with lodash 3. However, in package.json lodash 3 is [specified](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-table/package.json#L44) as supported version.

Please, use `import {isFunction} from 'lodash'` way of importing utils or change versions in package.json

**Comment by bebraw** [comment]
I have documented potential fix [here](http://reactabular.js.org/#/installing). Does lodash recommend some certain import style?

**Comment by apsavin** [comment]
Well, it's a workaround, but the fact that workaround exists doesn't make reactabular compatible with lodash 3 IMHO.
I'm not sure that lodash recommends some certain import style. I personally prefer `'lodash/%methodName%'`.

Feel free to close the issue if disagree)

**Comment by bebraw** [comment]
Ok, I'll get some external opinions on this. If you can link me to a library that deals with this well, that would be great.

I don't mind changing the imports.

**Comment by jdalton** [comment]
There is no compatible v3 or v4 import path. Simply drop the v3 mention in the docs. v3 is no longer maintained (no bug fixes applied to it).

**Comment by bebraw** [comment]
@jdalton Thanks. I think I'll refactor the imports to a simpler format (`import { find } from 'lodash';`) and document the version minimum.

**Comment by jdalton** [comment]
You could use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to make things easier.
