### ISSUE TITLE
Working with dates: need to filter on more than the ISO datestring

### ISSUE THREAD

**Issue by melissanoelle** [reactabular/reactabular#227]
We're using Reactabular and it's been pretty great, thanks!

However, we're having a bit of trouble with dates. Our date is outputted to us as an ISO datestring (example: `2016-10-24T22:27:15+00:00`), and we want to be able to filter but allowing the user to type `oct` into the filter input and still have those dates appear.

We cannot just change the value of the property, because then sorting would break--it would be alphabetical by month name rather than by date.

My initial thought was to change the value that Reactabular uses to filter on by appending the human-readable date that we display in the `cell: { format: (date) => { return formatDate(date) } }` JSON object that we build (we are using Redux) so that the filtering will work without breaking sorting, but I can't find a way to do that.

Can you help? Is there a better way?

Thanks.

**Comment by bebraw** [comment]
Hi,

Cool to hear you have found the component useful.

[Resolution logic](http://reactabular.js.org/#/data/resolving) was designed this use case in mind. Especially `resolve.byFunction` might fit. You can see it in action at the [all features example](http://reactabular.js.org/#/examples/all-features).

Using a resolver you could define a field like `resolve: date => formatDate(date)`. The internal logic respects resolved fields through a convention.

Let me know how it goes.

**Comment by melissanoelle** [comment]
Hey, thanks for the response.

I'm having a hard time understanding your docs on this. I added the `resolve: date => date + ' ' + formatDate(date)` bit that we need, but getting Reactabular to resolve it is proving difficult.

I added this to our `compose()` function:

```
resolve.resolve({
  columns: this.props.columns,
  method: ({ column }) => resolve.byFunction('column.cell.resolve')
})
```

(I have also tried 'cell.resolve' inside the `resolve.byFunction()` method because the docs list both ways.)

But it doesn't work. Additionally, I added a `console.log()` call within the `resolve` method that I added above just to see if it's being called, and it never gets triggered.

I tried reading your source code as well, and still didn't have much luck in understanding what I need to do to get the resolve to work.

Can you provide an example of the `resolve.byFunction` working without any other examples mixed in with it? The all features example uses a nested resolve, and between that and all the other features added into that example it seems like it's muddying my understanding of exactly what I should be doing.

Thanks.

**Comment by bebraw** [comment]
Hi,

I think you want something along

```javascript
resolve.resolve({
  columns: this.props.columns,
  method: resolve.byFunction('cell.resolve')
})
```

I hope that helps.

Note that you can extract the transformation portion to a function to test against. It's easier to see what's going on then.

I agree adding standalone examples to the documentation would be beneficial.

**Comment by bebraw** [comment]
Hi,

Reactabular 8 introduces a neater way to compose resolvers. You can do something like

```javascript
import { compose } from 'redux';

...

const resolver = resolve.resolve({
  columns,
  method: (extra) => compose(
    resolve.byFunction('cell.resolve')(extra),
    resolve.nested(extra)
  )
});
```

Far neater than earlier.

**Comment by bebraw** [comment]
Time to close. Feel free to re-open if still relevant.
