### ISSUE TITLE
How to specify colspan for cell 

### ISSUE THREAD

**Issue by Suprit-S-M** [reactabular/reactabular#230]
How to specify colspan for cell . I know using cell property w can do , I could able to change the cell width using cell property but not able to find how to specify colspan for cell . If you assist me to solve this problem , it would be great help for me.

**Comment by bebraw** [comment]
Can you provide more information? Some visualization might help.

Now header level colspans are managed by Reactabular and it's not possible to override. That would be easy to change, though (need to swap two lines at `resolve-header-rows`), but this in turn would break children column calculation if you override.

**Comment by Suprit-S-M** [comment]
Thanks for your time, Lets say we have 10 columns(headers) , first header cell has some value after that next 5 header cells doesn't have any value(means blank), I would want to use that space and display first cell value by doing colspan=6 for first cell . This is the requirement . For example,

Header1 Header2 Header3 Header4 Header5 Header6 Header7 Header8 Header9 Header10
ahsjsjskdkklkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk              10           20          30           40

**Comment by mudrila** [comment]
So, it is possible to change colspan of cell, but not for header? Is it still valid?

**Comment by bebraw** [comment]
@mudrila Based on https://github.com/reactabular/reactabular/commit/c9ab553114233889e45239d5eeb5eb69e4010358 I would say it's possible to override for both.

**Comment by mudrila** [comment]
@bebraw It works correct for cell, but it pass `colspan` not to `th` tag, but to `span` inside it

**Comment by bebraw** [comment]
@mudrila Ok, it could be a bug then. Could you set up a separate issue with an example I can run? Or if you have time, PR a fix. 👍

**Comment by mudrila** [comment]
I will setup issue, and in addition will try to create PR.

**Comment by mudrila** [comment]
Sorry, it was problem inside my code
