### ISSUE TITLE
Modify the style of a single cell

### ISSUE THREAD

**Issue by jphamilton** [reactabular/reactabular#231]
I'm in the process of trying to update reactabular in our app (0.11.2 ancient times I know) to the latest release. The only issue I am having is that there doesn't seem to be a way to modify the style of a single cell.

The old releases allowed cell to be a function where you could return:
{
   value: <Component />,
   props: {....}
}

I can't seem to find the equivalent in the latest version.

**Comment by bebraw** [comment]
If it's all cells, write an override. More: https://reactabular.js.org/#/table/overriding-default-elements .

If it's only some specific type, override at definition `props`: https://reactabular.js.org/#/column-definition/cell . There is also a hook that captures header as well. Literally column level `props`.

I hope one of these works for you.

**Comment by jphamilton** [comment]
It's not either of these scenarios. It's specific cells that meet a certain condition. Look at the red/yellow cells here: http://imgur.com/igxcb2J.

P.S. I did not design this ugly app

**Comment by bebraw** [comment]
Ok. If you want to attach to a `td` based on a rule, custom transform would cut it. See https://reactabular.js.org/#/column-definition/transforms .

**Comment by jphamilton** [comment]
That was it! Thanks so much.

**Comment by bebraw** [comment]
No probs. I think I'll add a mention to the styling docs.
