### ISSUE TITLE
[Feature] Add fixed column

### ISSUE THREAD

**Issue by davidtzoor** [reactabular/reactabular#232]
First of all - great job with this package!
Sometimes you need the first `n` column fixed while you scroll horizontally, so you emphasize on specific data while scrolling (e.g. name column). 
Here is an example from [DataTables](https://datatables.net/extensions/fixedcolumns/examples/initialisation/simple.html)

**Comment by bebraw** [comment]
More reference: http://stackoverflow.com/questions/1312236/how-do-i-create-an-html-table-with-fixed-frozen-left-column-and-scrollable-body

**Comment by bebraw** [comment]
There's an example of how to implement this at https://reactabular.js.org/#/examples/fixed-columns now.
