### ISSUE TITLE
How to show cell value on hover on cell along with header name

### ISSUE THREAD

**Issue by Suprit-S-M** [reactabular/reactabular#234]
How to show cell value on hover on cell along with header name.

**Comment by bebraw** [comment]
Hi,

That's an interesting question. I can see a couple of options. The simplest would be to use something standard like `abbr` (standard element) and set it up to show the data.

You get cell level data and property name at `format` and `transforms`. That should be enough for the data side.

Combining these two should be enough. This would make a great demo so let's retain this open for now.

**Comment by Suprit-S-M** [comment]
Ok thank you , Yeah I made it work using abbr element , But how to use multiple setting in format, I mean for example ,

format:tree.toggleChildren({})  , I would want to implement abbr tooltip for the same cell using same foramt 

I am trying to use it like 
format:[ree.toggleChildren({}) , (value, { rowData }) => ( <abbr  title={rowData.name}>{rowData.name}</abbr>) ] , but this is not working .

**Comment by bebraw** [comment]
Hi,

`format` doesn't accept an array. It's expected to return something React can render as described at https://reactabular.js.org/#/column-definition/formatters .

I would try something along this:

```javascript
format: (value, extra) => (
  <abbr ...>
    {tree.toggleChildren(value, extra)}
   </abbr>
)
```

Since `tree.toggleChildren` returns a React element, the above should work.

**Comment by Suprit-S-M** [comment]
Thank you , but it did not work in my case

**Comment by bebraw** [comment]
@Suprit-S-M Can you give an example of what you tried? Look very carefully in the second parameter (`extra`). It would be good to have some code to work with.

**Comment by bebraw** [comment]
Please re-open if you can get a little example done. 👍
