### ISSUE TITLE
How do you insert two property values in a single cell

### ISSUE THREAD

**Issue by lynxfx** [reactabular/reactabular#235]
I would like to make one cell contain a link. The display value would be **name** and the url would be provided by a property **url** in the dataset. 

Using the format below I can get in display value "Google" in the cell do not know how to insert the url.

```javascript
rows: [
    {
        name: 'Google',
        url: 'http://www.google.com'
    }
]

columns: [
   {
       property: 'name',
       header: {
           label: 'Website'
       },
       cell: {
           format: (value) => (
               <a href="?">{value}</a>
           )
        }
     }
]
```

**Comment by bebraw** [comment]
Try something along `format: (value, { rowData: { url } }) => (`. More info: https://reactabular.js.org/#/column-definition/formatters .

**Comment by lynxfx** [comment]
Thank you that worked.
