### ISSUE TITLE
How to change the cell background color based on condition

### ISSUE THREAD

**Issue by Suprit-S-M** [reactabular/reactabular#236]
I would want to change the cell  background color based on some condition . I have made it work by creating html tag inside cell , but I would want change the cell bgcolr without creating another tag

**Comment by bebraw** [comment]
@Suprit-S-M Can you provide an example of what you have so far?

I think a custom [transform](https://reactabular.js.org/#/column-definition/transforms) should be able to do the trick. You need to perform the check there and pass `style` containing the color based on your logic. That will inject to the table cell.

**Comment by Suprit-S-M** [comment]
Ok thanks for your time , its really helps me.

**Comment by bebraw** [comment]
No probs. Keep me updated. 👍

**Comment by Suprit-S-M** [comment]
yeah sure

**Comment by Suprit-S-M** [comment]
Hello , How to make by default cell edit should show edit box , Currently once I click on cell edit box is getting displaying . I want to show it without clicking . Could you please help me.

**Comment by bebraw** [comment]
@Suprit-S-M I think they key is in controlling the `isEditing` flag. See the [demo](https://reactabular.js.org/#/data/inline-editing). Basically you would have to set the state so that the function evaluates as true by default to achieve what you want.

**Comment by Suprit-S-M** [comment]
We can not set the state during render , I am not getting it how to do , Could you please help me to get it done.Because isEditing will call every reneder(cell display).

**Comment by bebraw** [comment]
@Suprit-S-M I'm going to need some code to tell any better. I don't mind getting you guys on some kind of support plan if you want.

**Comment by Suprit-S-M** [comment]
Yeah thanks for your time , I made it work ,  Thank you

**Comment by bebraw** [comment]
Ok, cool. Let's close this one then.
