### ISSUE TITLE
Remove filter from certain columns.

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#240]
I want to remove filter from certain columns. For a table displaying three columns like the one below:

```
[
        {
          property: 'name',
          header: {
            label: 'Name'
          },
          visible: true
        },
        {
          property: 'type',
          header: {
            label: 'Type'
          },
          visible: true
        },
  	    {
          property: 'number',
          header: {
            label: 'Number'
          },
          visible: true,
          filter: false
        }
]
```

Specifying filter=false on number should prevent filter from being displayed.

**Comment by bebraw** [comment]
Let's say you have

```javascript
<SearchColumns
  query={query}
  columns={columns}
  onChange={query => this.setState({ query })}
/>
```

Wouldn't the following do the trick?

```javascript
<SearchColumns
  query={query}
  columns={columns.map(column => ({
    ...column,
    property: column.filter === false ? null : column.property
  }))}
  onChange={query => this.setState({ query })}
/>
```

`SearchColumns` should render nothing if `property` isn't set so mapping and changing the fields that way should make the filters disappear.

I am not sure if adding the feature there would be worthwhile as you can handle the concern outside of the component.

**Comment by vijayst** [comment]
Thanks @bebraw. That worked! 

It is not obvious to set property to null if I don't want filter! My code looks like this:

```
   const visibleColumns = columns.filter(column => column.visible);
    const searchColumns = visibleColumns.slice();
    if (edit) {
      searchColumns[0].property = null;
    }
```

**Comment by bebraw** [comment]
Yeah, I would welcome a documentation PR if you have to plug something in. 👍

**Comment by vijayst** [comment]
The code got a bit ugly. The column has to be cloned and then the property should be nulled. This will ensure that the values are available. Given the ugliness of the below code, an additional filter property (true | false) should be much neater to prevent a specific column from being filtered.

```
    const searchColumns = visibleColumns.slice();
    if (edit) {
      searchColumns[0] = Object.assign({}, searchColumns[0]);
      searchColumns[0].property = null;
    }
```

**Comment by bebraw** [comment]
That's a little sketchy, yeah. Maybe `SearchColumns` could accept a separate prop that would accept an array of visible columns.

I do like the idea of having that information encoded within column definition, though. Based on that another option would be to expose filtering logic that it uses while rendering.
