### ISSUE TITLE
Clickable links and onRow not working well together.

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#242]
I have a clickable link in a column. I am handling row selection using onRow. On clicking the link, the onRow is also triggered. Is there any way to prevent onRow from being triggered for certain columns?

**Comment by bebraw** [comment]
I would need a little example to tell any better. I have something going on [here](https://reactabular.js.org/#/features/selecting-rows).

Why is triggering `onRow` an issue? You should not have any direct logic that gets executed when it's called but you can attach things like row level `onClick` handlers there for dealing with selection.

**Comment by vijayst** [comment]
The recording below shows the problem that I am facing. 
![reactabular-select](https://cloud.githubusercontent.com/assets/3457565/20455719/62fba1d6-ae88-11e6-9872-5f74938f1388.gif)

On selecting the rows, I am displaying the detail of the row above. That works fine. I have a checkbox column to the right. The checkbox column is for selecting multiple rows to perform delete. While selecting the row via checkboxes, the detail continues to change. I prefer the detail not to change while selecting via checkboxes. In the contrived example, this is not a problem. For the project that I am working on, detail makes an API call. If select the checkbox, API calls are being made which I want to avoid.

The source code can be found in [https://github.com/vijayst/reactabular-select-demo](https://github.com/vijayst/reactabular-select-demo)

**Comment by bebraw** [comment]
Okay. So if I'm understanding right, clicking on "select" checkbox cascades to row selection as well. What if you stopped the event bubbling? You could try something like this:

```javascript
handleIdChange(e) {
  e.preventDefault(); // Stop bubbling

  // ... do your thing
}
```

**Comment by vijayst** [comment]
The first event that is being handled is the onRow. After onRow completes, checkbox event is being handled!

**Comment by bebraw** [comment]
Alright, figured it out. You can do a check like this:

```javascript

onRow(row, { rowIndex }) {
  console.log('on row');
  return {
    className: row.selected && 'selected-row',
    onClick: (e) => this.onSelectRow(e, row, rowIndex)
  };
}

onSelectRow({ target: { tagName } }, row, rowIndex) {
  // Skip selecting if clicked on input
  if (tagName === 'INPUT') {
    return;
  }

  const { rows } = this.state;
  const { id, name, age } = row;
  console.log('select row');
  this.setState({
    id,
    name,
    age,
    rowNumber: rowIndex + 1
  });
}
```

It has something to do with the way DOM has been specified. It gives you `target` to check against. If you detect it's input, you can skip the default behavior.

**Comment by vijayst** [comment]
Thanks @bebraw. It is very helpful.
