### ISSUE TITLE
https://reactabular.js.org/ on IE11 KO

### ISSUE THREAD

**Issue by FredericHeem** [reactabular/reactabular#244]
Just to let you know that https://reactabular.js.org/ is not displaying on IE11:

```
SCRIPT438: Object doesn't support property or method 'defineProperty'
SCRIPT438: Object doesn't support property or method 'isArray'
```

It is fine on Edge.

**Comment by bebraw** [comment]
Thanks. I guess those might need some shims.

**Comment by bebraw** [comment]
That `isArray` bit should be gone. At least I refactored it out of the code so hopefully that error is gone.

**Comment by bebraw** [comment]
Can you check now? At least the array bit should be gone. I'm not sure what to do with the other.

**Comment by bebraw** [comment]
I'm closing this for now. Please re-open if you can confirm.
