### ISSUE TITLE
Does reactabular support ie9?

### ISSUE THREAD

**Issue by redguardtoo** [reactabular/reactabular#245]
I checked some sample code. Looks it supports IE9, just want to double check with you. Thanks in advance.

**Comment by bebraw** [comment]
I would say it depends on React and lodash. You may also need to shim features like `Array.isArray`.

Ideally we would run the test suite against IE9 to know for sure.

**Comment by redguardtoo** [comment]
I checked Lodash and React version. They still support IE9. As for the `Array.isArray` concern, I installed es5-shim. I will report you the result.

**Comment by bebraw** [comment]
@redguardtoo Did you check? How did it go?

**Comment by redguardtoo** [comment]
Yes, it's working on IE9, Win7. I install es5-shim v4.5.9, es6-promise 4.0.5, whatwg-fetch 0.11.1 (new version of whatwg drop the IE9 support)
