### ISSUE TITLE
Website Demo Column Visibility Broken

### ISSUE THREAD

**Issue by jeff-wolff** [reactabular/reactabular#252]
https://reactabular.js.org/#/examples/all-features

On this page the column visibility checkboxes are broken

and on this page it has weird functionality and doesn't work on mobile: 
https://reactabular.js.org/#/easy

**Comment by bebraw** [comment]
Thanks. I fixed the column visibility problem.

I have to check the easy example on mobile to get a better idea. Maybe I should simplify that example further. There's too much going on.

**Comment by bebraw** [comment]
Cool. Feel free to join me at [Gitter](https://gitter.im/reactabular/reactabular) if you have any specific questions.

**Comment by bostondevin** [comment]
https://reactabular.js.org/#/easy 

The checkboxes aren't working properly here - they don't ever uncheck

**Comment by bebraw** [comment]
@bostondevin Fixed. Thanks. I was digging the visibility data for the widget in a wrong way. Having stronger typings (TypeScript) would catch these I think.

**Comment by bostondevin** [comment]
@bebraw Thanks!!!

**Comment by bostondevin** [comment]
@bebraw - hey just noticed this too - it's probably related - in the Search dropdown - you can't seem to change the select option from All - looks like it's stuck. I can add a bug for this if u like. Thanks

**Comment by bebraw** [comment]
@bostondevin It was missing some wiring. Fixed now. Thanks!

**Comment by bebraw** [comment]
I think it's time to close this. Please open separate issues if you notice anything else.
