### ISSUE TITLE
Columns off by 1 for examples it seems

### ISSUE THREAD

**Issue by Souvent22** [reactabular/reactabular#253]
I'm having some issues with the simple examples. 

Take the example outlined here: 

https://github.com/reactabular/reactabular/tree/master/packages/reactabular-table  

When I use that example, the table header renders fine, however none of the rows render. Specifically, there are X rows for the X pieces of data, so that matches, but all rows are empty. 
The only way I can get around this is by adding: 
```javascript
cell: {
  property: 'name'
}
```
To each header item. 

However, even after doing this, the table is off by one. Meaning, there is 1 empty vertical column, and then the name shows up under the empty header, and the `Dad` shows up under name, with 1 column just hanging with nothing. I have attached a screen shot to demonstrate what I mean.
![image](https://cloud.githubusercontent.com/assets/253601/20983428/6cdb66f4-bc8a-11e6-90be-081c798024fb.png) 

The code that's producing this is:
```javascript
  getTableListing() {
    const rows = [
      {
        id: 100,
        name: 'Adam',
        dad: 'John',
        lovesBeeGees: true
      },
      {
        id: 101,
        name: 'Brian',
        dad: 'George',
        lovesBeeGees: false
      }
    ];

    const columns = [
      {},
      {
        property: 'name',
        header: {
          label: 'Name'
        },
        cell: {
          property: 'name'
        }
      },
      {
        property: 'dad',
        header: {
          label: 'Dad'
        },
        cell: {
          property: 'dad'
        }
      }
    ];
    return (
      <div className="section-panel">
        <Table.Provider
          className="pure-table pure-table-striped"
          columns={ columns }
        >
          <Table.Header />

          <Table.Body rows={ rows } rowKey="name" />
        </Table.Provider>
      </div>
    );
  }
```

Does anyone have any thoughts?

**Comment by bebraw** [comment]
Hi,

It's because of

```javascript
const columns = [
      {},
      ...
];
```

Removing that empty column definition (`{}`) should fix the issue.

**Comment by Souvent22** [comment]
When I remove that though, it's still off by one...let me get a screen shot of it. I'll get one in a second...looking into the source real quick to see if I can trace what's happening.

**Comment by Souvent22** [comment]
Darn, thought I had found it. But yeah, if I remove the first empty column, it results to this: 

![image](https://cloud.githubusercontent.com/assets/253601/20985590/1cf0919c-bc93-11e6-8667-167bdb7fff72.png)

**Comment by Souvent22** [comment]
But I think I figured out what was interfering :). 
Closing this as user error. 
Thanks for a quick response.
