### ISSUE TITLE
sort using external button

### ISSUE THREAD

**Issue by pepepaco** [reactabular/reactabular#254]
Im trying to sort the table based on a buttongroup that is outside the component, this is the reactabular table:
`<AllFeaturesTable sortBy={isActive} dataSource={getRows} />`

this buttongroup pass the **isActive** value to the reacttabular state: 
```
this.state = {
      rows: this.props.dataSource, // initial rows
      sortingColumns:props.sortBy, // initial sort     
      columns: this.getColumns(), // initial columns
    };
```
to sort the data based on this value I change the sortingColumns in the **render** method:
```
this.state.sortingColumns=this.props.sortBy;
const sortedRows = compose(     
      sort.sorter({ columns: cols, sortingColumns, sort: orderBy })
    )(rows);

```
the initial sort works as expected.. but... if I click the button group again, the header is updated with the new sort, but the data is not, I have to click the button twice to get the data sorted.

where should I change the sortingColumns so the data is sorted without having to click the external button twice??

Also, the value pass to the reactabular table comes from the store, I dont have access to the click event.
If I print the props.sortBy or this.state.sortingColumns to the console the value is correct every time i click the button, but If I print the sortingColumns  field instead of this.state.sortingColumns its value is lagging behind for one click, I cant change sortingColumns on the render method, I can only change this.state.sortingColumns because is readonly.
 
thanks!

**Comment by bebraw** [comment]
Can you set up a standalone example (a GitHub repo would do) to study? It's a lot easier to tell what's going on then.

**Comment by pepepaco** [comment]
thank you I have uploaded a simple example here:
https://github.com/pepepaco/react-webpack-babel/blob/master/src/components/topSellingTable.js
at line 135 i describe the issue, 

basically this lines are the following:
```
    //trying to change sort order by updating the state directly:
   this.state.sortingColumns=this.props.sortBy;  
    //this property has the correct value
    console.log("this.state.sortingColumns="+this.state.sortingColumns);
    //this property lag by one click
    console.log("sortingColumns="+sortingColumns);
```
where this.props.sortBy; is the parameter pass by the toggle button.
the state referenced as this.state.sortingColumns is also correct, but
the state pass to the sort like this sortingColumns; lags one click behind.

I'm pretty sure my code is a huge mess, i'm just learning on the way i'm working at this. 
any help would be appreciated

**Comment by bebraw** [comment]
That `this.state.sortingColumns=this.props.sortBy;` goes against the way React works. It's far better to modify state through `this.setState`. Note that it's async and will trigger `render()` eventually unless `shouldComponentUpdate` tells otherwise.

I'll try to find time tomorrow to run the code to tell more.

**Comment by pepepaco** [comment]
thank you for the quick answer, I tried to use this.setState inside the render method but it falls into an infinity loop and breaks.  I also tried to put this.setState inside a custom BodyWrapper.shouldComponentUpdate but it has the same issue of being one click delayed, also the grid is not updated with the new state... 
 
besides the sorting by external button, in the near future Ill need to update the data dynamically, that is, if the data change, update the reactabular automatically, I haven't tried that yet. I just wonder if that will be possible also. 
regards.

**Comment by pepepaco** [comment]
I have got the desired results by updating the data instead of using the sorting functionality since at the end of the day Ill refreshing this data dynamically, 
I just applied the loadash orderBy function to the data, and then passed this data to reactabular.
Ill need sort the local data anyway but that will be by clicking on the header. 
Ill need just to update the header to show the correct order by flag when is done by the external button.
Thanks!

**Comment by pepepaco** [comment]
I had to remove the sorting from the other columns since adding the data sorted, breaks the functionally of reactabular. by now im fine as it is, but to update the header I had to left this line otherwise the header flag is not updated: line 136 in https://github.com/pepepaco/react-webpack-babel/blob/master/src/components/topSellingTable.js

`this.state.sortingColumns=this.props.sortBy; `

thanks,

**Comment by bebraw** [comment]
I see now. Maybe it would be cleaner to add a callback prop and then push `sortingColumns` outside of the table. That would remove the need for `this.state.sortingColumns` and it would clean up the code somewhat. You would avoid `this.state.sortingColumns=this.props.sortBy` in this case.
