### ISSUE TITLE
cannot find module lodash?

### ISSUE THREAD

**Issue by noahehall** [reactabular/reactabular#255]
<img width="447" alt="screen shot 2016-12-09 at 9 22 52 am" src="https://cloud.githubusercontent.com/assets/10324554/21058067/1f97f656-bdf1-11e6-85f4-3154fb2eb31b.png">

<img width="431" alt="screen shot 2016-12-09 at 9 23 25 am" src="https://cloud.githubusercontent.com/assets/10324554/21058073/2c92b80a-bdf1-11e6-9278-37cb0584f2a8.png">

**Comment by noahehall** [comment]
The issue is fixed if  i change:
`import * as Table from 'reactabular-table';`

to this:
`import * as Table from 'reactabular';`

but then I get this console warning:
`Please use Reactabular through separate packages! See reactabular.js.org for more information
Server running: http://localhost:3000`

**Comment by bebraw** [comment]
Hi,

It expects to find `lodash` 4 as a peer dependency. Have you included it to your project? I could use more information. Standalone project would be ideal.

**Comment by bebraw** [comment]
`import * as Table from 'reactabular';` is deprecated. The structure was split up in v8.

**Comment by noahehall** [comment]
thank you @bebraw 

I needed to include lodash

**Comment by chazzlabs** [comment]
I just ran into this as well.  This should probably be included in the documentation somewhere, or at the very least, lodash v4.x should be listed as a peer dependency in package.json.

**Comment by bebraw** [comment]
@chazzlabs Thanks for the heads up. I bumped the peer deps to v4 minimum since it just won't work with 3. If I understood right, v5 will follow similar conventions (drops some functionality, though).
