### ISSUE TITLE
Can reactabular handle thounsands of rows?

### ISSUE THREAD

**Issue by redguardtoo** [reactabular/reactabular#256]
The browser is IE11 or Latest Chrome, the actual rows number could reach 10K, there are about 35 columns (one month data).

Any suggestions on performance?

**Comment by bebraw** [comment]
Are you using [virtualization](https://reactabular.js.org/#/features/virtualization)? Enabling that can make a big difference.

**Comment by redguardtoo** [comment]
Thanks for the tip. Looks pretty cool. I will try it tomorrow.

**Comment by bebraw** [comment]
Time to close.

In addition to virtualization, you can look into improvements at data processing side. It can be pushed to a worker, memoized, and so on depending where the slowness happens to be.
