### ISSUE TITLE
scrollbar on the sticky table header?

### ISSUE THREAD

**Issue by redguardtoo** [reactabular/reactabular#257]
Our designer want to remove the scroll bar below the header when using sticky header table. Is it doable?

**Comment by bebraw** [comment]
You can try overriding the default `overflow` through `style` prop. Let me know how it goes.

**Comment by redguardtoo** [comment]
Thanks. It works.

```html
          <Sticky.Header
             style={{
               maxWidth: 1024
               overflow: 'hidden'
             }} />
```
