### ISSUE TITLE
cell in sticky not aligned with header when scrolling to the right end

### ISSUE THREAD

**Issue by redguardtoo** [reactabular/reactabular#259]
Cell and header are aligned most time, but when I scroll almost to the right end and **if and only if the scroll bar in Y direction exists**, the cell and header are not aligned.

- can be reproduced on ie11, latest firefox
- reactabular-sticky 8.2.0, reactabular-table 8.1.0
- column width is pre-calculated and big enough to hold the data

Screenshot BEFORE scrolling to the right end,

![before](https://cloud.githubusercontent.com/assets/184553/21169776/613ea462-c213-11e6-8ff6-50b253a8aa26.png)

AFTER:
![after](https://cloud.githubusercontent.com/assets/184553/21169788/728502de-c213-11e6-8256-2b65fd039a2b.png)

**Comment by bebraw** [comment]
The problem is that `Sticky.Body` needs to take that scrollbar into account, but for some reason I don't know yet, the calculation can fail. You can see the basic idea [here](https://github.com/reactabular/reactabular/blob/d3b0a48ac137a2f20317c19f9d035a15cad6f41c/packages/reactabular-sticky/src/body.js). It's that `const scrollOffset = tableHeaderWidth - tableBodyWidth || 0;` bit.

If you want to study it, that would be the place. PR would be very welcome as I'm going to be a little busy for a while.

**Comment by redguardtoo** [comment]
Hi, @bebraw 
I did some investigation.

The scrollLeft is fine. When there is scrollbar, the bar has to scroll a little bit in right direction because the content shadowed by scroll bar need be fully visible. 

But header already used up its "buffer", it can't scroll to the right any more.

The solution is simple, **if and only if the view can't display all the columns (so scrollbar-x is required), the column width of last column should plus the width of the scrollbar**.

Could you show me where to change the last column width dynamically?

**Comment by bebraw** [comment]
Hi,

reactabular-sticky deals with it. See [here](https://github.com/reactabular/reactabular/tree/master/packages/reactabular-sticky). The corresponding example is [below features](https://reactabular.js.org/#/features/sticky).

**Comment by bebraw** [comment]
Table body does calculation already. I think the problem is that there's a race condition so rendering doesn't stay in sync. It's going to need something extra to deal with that problem (some trigger somewhere?).

**Comment by redguardtoo** [comment]
After second thought, I think the solution should be handled outside of reactabular. Because the user of reactabular got all the information and it's easy to implement out side of reactabular.

Here is the sample code which I've already tested.

The basic idea is increase the extra 16px (width of scrollbar) to the last column's header when there is x scroll bar.

```javascript
import React from 'react';
import { findDOMNode } from 'react-dom';
import * as Table from 'reactabular-table';
import * as Sticky from 'reactabular-sticky';

export class MyTable extends React.Component {
  constructor(props) {
    this.state = {
      rows: [],
      cols: []
    };
  }

  tweakLastColumnHeader() {
    var header = findDOMNode(this.tableHeader);
    var columnHeaders = header.querySelector('tr').querySelectorAll('th');
    if(!columnHeaders || !columnHeaders.length) {
      return;
    }
    var lastColumnHeader = columnHeaders[columnHeaders.length - 1];
    var originalColumnWidth = 160, scrollbarWidth = 16;
    lastColumnHeader.style['min-width'] = (originalColumnWidth + scrollbarWidth) + 'px';
  }

  getColumns() {
    var cols = [];
    // ....
    setTimeout(this.tweakLastColumnHeader.bind(this), 1000);
    return cols;
  }

  generateRows() {
    return [];
  }

  componentDidMount() {
    this.setState({
      cols: this.getColumns(),
      rows: this.generateRows()
    });
  }

  render() {
    return(
      <Table.Provider
        className="table table-stripped table-bordered"
        columns={this.state.cols}
        >
        <Sticky.Header
          style={{
            maxWidth: 1024 /*table width*/,
            overflow: 'hidden'
          }}
          ref={tableHeader => {
            this.tableHeader = tableHeader && tableHeader.getRef();
          }}
          tableBody={this.tableBody}
          />
          <Sticky.Body
            rows={this.getRows()}
            rowKey="id"
            style={{
              maxWidth: 1024 /*table width */,
              maxHeight: 768 /* table height */
            }}
            ref={tableBody => {
              this.tableBody = tableBody && tableBody.getRef();
            }}
            tableHeader={this.tableHeader}
            />
      </Table.Provider>
    );
  }
}
```
setTimeout(this.tweakLastColumnHeader.bind(this), 1000);

**Comment by bebraw** [comment]
That's an interesting point. I would still love to see a nice solution (a package?) for this that could be dropped in.

**Comment by redguardtoo** [comment]
Though my previous solution works around  the alignment problem. There is a corner case I found yesterday.

My old solution increases the header width of last column a little bit by hacking DOM directly. If the column position is the re-adjusted,  the original last column will be in the middle of tables, So we create a new alignment issue because in that middle column header width is greater than cell width. 

The clean solution is in table body onScroll callback, force the e.target.scrollLeft never reach the maximum value if could reach.
