### ISSUE TITLE
Highlight a formatted cell

### ISSUE THREAD

**Issue by Ezekiah** [reactabular/reactabular#260]
Hello,
From my database I get a rowdata, a string with separators which I need to split, I do as folow : 

```
cell: {
        	
         property:'messages',
          formatters: [(value, { rowData }) => {
          	
          	var messages = rowData.messages.split('$$$$$');
          	
          	var m_array = [];
          	_.each(messages, (m)=>{
          		m_array.push(<div>{m}</div>)
          	})
          
          	
        		return (
        			<div style={{'maxHeight':'100px', 'overflow-y':'scroll'}}>{m_array}</div>
	          )


          }, search.highlightCell]
        },
        visible: true
      }

```

However when I do that It writes [object, object] in the td, how can I highlight a formatted result of a column please ?

**Comment by bebraw** [comment]
Hi,

It's quite possible you need to [resolve the data](https://reactabular.js.org/#/data/resolving) first. Highlighting and all logic is resolve aware and it was designed for cases just like this where the data you receive and want to display aren't the same.

**Comment by Ezekiah** [comment]
Ok,

For the moment I did like this, but it's a bit buggy : 
```
cell: {
        	
        	property:'messages',
          formatters: [(value, extras) => {
          	
          	var messages = extras.rowData.messages.split('$$$$$');
          	
          	var m_array = [];
          	_.each(messages, (m)=>{
          		m_array.push(<div>{search.highlightCell(m,extras)}</div>)
          	})
          
          	
        		return (
        			<div style={{'maxHeight':'100px', 'overflow-y':'scroll'}}>{m_array}</div>
	          )


          }]
        },
        visible: true
      }
```

**Comment by bebraw** [comment]
It's likely easier if you push the data concern outside of `cell`. You have to partition the problem somehow and understand how the individual parts work. I can't give any more specific advice without having code to run.

**Comment by Ezekiah** [comment]
I'm just using the full example from the website, I just added this cell, the rowdata is like this : message$$$$$message2$$$$$message3$$$$$message4. 
For the moment when I search it returns all matches but all message rows are hightlighted.

**Comment by bebraw** [comment]
That's another reason why it's important to resolve the data. If you skip the resolving pass, then search and highlight operate under different assumptions.

**Comment by Ezekiah** [comment]
I will try to understand data resolving :)

**Comment by bebraw** [comment]
`resolve.byFunction` is most likely what you need. That allows you to map a field with a function containing a resolver to a resolved value. So you would massage that rowdata to a good format right there.
