### ISSUE TITLE
onRow not re-evaluated when new props received

### ISSUE THREAD

**Issue by hwaterke** [reactabular/reactabular#265]
I'm using `this.props` inside my `onRow` function.
The problem I'm facing is that the `onRow` function is not evaluated when the component receives new props.

```javascript
onRow(row) {
    return {
      className: this.props.selectedRows.has(row.id) && 'selected-row'
    };
  }
```

Is this the expected behaviour?
If yes, how can I make it work?

Thanks in advance, very nice library ;)

**Comment by bebraw** [comment]
Hi,

The default SCU is fairly strict. You can override the behavior as explained [here](https://reactabular.js.org/#/table/overriding-should-component-update).

It might be interesting to make it easier to **extend** the default check somehow. I expect that would not require a big change. It's more of a design problem.

**Comment by hwaterke** [comment]
Ok I get it!
Now I understand why you update the `rows` in your selection example 🙂

Thanks and merry Christmas 🎄
