### ISSUE TITLE
Cannot find full list of props for each reactabular component

### ISSUE THREAD

**Issue by seleckis** [reactabular/reactabular#266]
Reactabular is awesome! But I cannot find a full list of supported props for components like Provider, Header, Body. Is there a list of all their props?

**Comment by bebraw** [comment]
Hi,

[Table component docs](https://reactabular.js.org/#/table/components) should cover the most. `Provider` also has support for [component overrides](https://reactabular.js.org/#/table/overriding-default-elements). You can find the entire schema [here](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-table/src/types.js).

**Comment by seleckis** [comment]
Thank you. That would be usefull to add types.js in docs as table with human-readable explanation.

**Comment by bebraw** [comment]
Sure, let's leave this open for now.

I have focus on other things right now, but if you want to do an initial PR to tweak, that would be great.

**Comment by bebraw** [comment]
The props should be covered by now I think. If there's something missing, please PR.
