### ISSUE TITLE
How to show an image in a cell?

### ISSUE THREAD

**Issue by seleckis** [reactabular/reactabular#267]
I tried to use formatters. It is ok if I use property as a trigger that I should format content as image. But what if an image could be in any column? Tried to use dangerouslySetInnerHTML, but it is not allowed, because:

> Can only set one of `children` or `props.dangerouslySetInnerHTML`.

There is no example in docs.

Any suggestion?

**Comment by bebraw** [comment]
Hi,

Something along

```javascript
formatters: [
  (src) => <img src={src} />
]
```

should do the trick. Formatters can return arbitrary JSX.

**Comment by seleckis** [comment]
Ok, I did it.
```js
	…
	handleRow(col) {
		const formatters = [];
		formatters.push((props) => {
			let element;
			if (typeof props === 'object') {
				if (props.image) {
					element = <img src={props.image} />;
				}
			} else {
				element = props;
			}
			return element;
		});
		if (formatters.length) {
			col.cell = {
				formatters: formatters
			};
		}
		return col;
	}
	…
```
in render:
```js
	const columns = headers.map((col, key) => {
		return this.handleRow(col);
	});
	<T.Provider columns={columns}>
	…
```
Thank you
