### ISSUE TITLE
Absolute search for filtering?

### ISSUE THREAD

**Issue by jeff-wolff** [reactabular/reactabular#268]
Hi I wanted to know if it's possible to do an absolute search with reactabular.

For example.. what if I want to find all the "Jack"s but not "Jackson" is there a way to filter for just "Jack"? In Google I would use quotes to designate absolute search.

**Comment by bebraw** [comment]
Hi,

The search logic is pluggable. See [searchtabular](https://github.com/reactabular/searchtabular) for details. It is possible it requires some kind of extension (a new hook?) to allow absolute matches. Feel free to continue there and we'll spec it out.
