### ISSUE TITLE
Indicator text for empty data

### ISSUE THREAD

**Issue by softage0** [reactabular/reactabular#269]
Sometimes notifying that there's no data is very useful in the middle of table or proper place.

It will be appreciated if it's implemented.

**Comment by bebraw** [comment]
Can you give an example? Is this UI-level or something only a developer sees?

**Comment by softage0** [comment]
UI-level. Just like the below:
![screen shot 2017-01-12 at 9 33 35 am](https://cloud.githubusercontent.com/assets/7719707/21873025/208ab08e-d8af-11e6-9aca-b7146b191410.png)

Of course, it can be implemented on user-level easily, but it'd be better if it's implemented on library-level.

**Comment by bebraw** [comment]
In the current design you can have multiple `Table.Body` elements. I think they render as empty if there's no data to render at the moment.

What if we did `<Table.EmptyBody rows={rows}>No data available</Table.EmptyBody>` or a similar helper to cover this case?

**Comment by softage0** [comment]
Yep, I just implemented it like the below:
```
{paginated.rows.length ?
    <table.Body onRow={this.onRow} rows={paginated.rows} rowKey="userId" />
    :
    <tbody><tr><td>No data available</td></tr></tbody>
}
```
(wrapped with tbody to apply same css as table.Body)

This way is not so bad, but I just thought it looks prettier if it provides as option :)

Thanks,

**Comment by bebraw** [comment]
Yeah, let's leave this outside of the core. You can wrap it on userland if you want.
