### ISSUE TITLE
import { generateRows} from "./helpers" not found

### ISSUE THREAD

**Issue by yuripramos** [reactabular/reactabular#274]
Hey =) 

I'm trying to install your library here in my application and your generaterows from the 'helper' are not being found. Anyway, I'm looking in the docs of https://reactabular.js.org/#/data/ and not finding an answer for this, actually I don't want to use generated values, I have a few values to start my table, but I have no idea how to input this in my store(change the generateRows for my rows instead)

Could you enlight me?

**Comment by bebraw** [comment]
Hi,

The helpers come from [here](https://github.com/reactabular/reactabular/tree/master/docs/helpers). You are not actually meant to use them. I'm primarily using them to generate mock data and handle basic tasks that go beyond the table implementation.

If you can set up a little example I can run, I don't mind having a look.

**Comment by yuripramos** [comment]
Thanks for your time @bebraw , now I'm trying to get the data from my custom json. Actually, I'm already able to do that, but when i load my custom json I cannot edit the fields, my console output that the editing is undefined. Tryin' to solve here, do you have any tip for this issue?
```


const predefinedRows = [
   { "combustivel" : "Flex",
  "imagem" : null,
  "marca" : "Volkswagem",
  "modelo" : "Gol",
  "placa" : "FFF-5498",
  "valor" : 20000
  },
  { "combustivel" : "Gasolina",
  "imagem" : null,
  "marca" : "Volkswagem",
  "modelo" : "Fox",
  "placa" : "FOX-4125",
  "valor" : "20000"
  },
  { "combustivel" : "Alcool",
  "imagem" : "http://carros.ig.com.br/fotos/2010/290_193/Fusca2_290_193.jpg",
  "marca" : "Volkswagen",
  "modelo" : "Fusca",
  "placa" : "PAI-4121",
  "valor" : "20000"
  }
  
];
```

**Comment by yuripramos** [comment]
I know the problem is in generate_rows.js, I'm trying not no mock the values and deliver my own values.

**Comment by bebraw** [comment]
I don't see anything obviously wrong in your data definition. I would have to see the Reactabular bits to say anything concrete. You can find the editing interface [here](https://github.com/reactabular/react-edit).
