### ISSUE TITLE
Reactabular Sticky simply not working

### ISSUE THREAD

**Issue by KevinMongiello** [reactabular/reactabular#275]
I've copy/pasted most of the example including 
- componentDidMount forceUpdate, 
- adding `this.tableHeader` & `this.tableBody` in constructor,
- added ref function inside Sticky.Header and Sticky.Body
- added props which cross reference Header and Body..

Still, my header columns shrink to approximately width: auto while my body columns are much wider due to amount of biggest cells.

**Comment by bebraw** [comment]
Can you set up a standalone example for me to study?

**Comment by KevinMongiello** [comment]
Yeah I'll try and put one together today

**Comment by Nighthawk22** [comment]
I fixed it with adding a fixed width:
```
const columns = [
  {
    property: 'number',
    props: {
        style: {
            width: 80
        }
    },
    header: {
      label: 'Number'
    }
 }]
```

Not really nice but it works.
