### ISSUE TITLE
Use style.maxHeight when height is undefined in virtualized table

### ISSUE THREAD

**Issue by redguardtoo** [reactabular/reactabular#276]
If height is undefined but maxHeight is defined, can Virtualized table use maxHeight instead?
```html
<Virtualized.Body
    onRow={this.onRow}
    rows={this.getRows()}
    rowKey="id"
    style={{maxWidth: this.stable.tableWidth, maxHeight: this.state.tableHeight}}
    ref={ tableBody => this.tableBody = tableBody && tableBody.getRef() }
    tableHeader={this.tableHeader} />
```

**Comment by bebraw** [comment]
The code explicitly relies on height at the moment. I'm not sure how something dynamic like `maxHeight` could work.

**Comment by redguardtoo** [comment]
My client don't display all the rows at the beginning, some rows are displayed after user click certain button. So if if I use height, the table will have some **extra empty space at the bottom of the table**. There are other UI components below the table, so the client prefer display the data in more compact way.

**Comment by bebraw** [comment]
Ok. A PR would be welcome. Maybe it takes a little extra math in some place.

**Comment by bebraw** [comment]
Merged. Forgot to close this at the PR.

**Comment by redguardtoo** [comment]
thanks
