### ISSUE TITLE
Percentage widths in sticky header and virtualized columns

### ISSUE THREAD

**Issue by skosch** [reactabular/reactabular#279]
I would like to use a virtualized table, and specify the column widths in percentages, not pixels. Is this possible with CSS, and if not, is there something I can hook into with a window resize handler?

**Comment by bebraw** [comment]
If I remember right, column widths should accept relative widths.

If you are using resizing I guess the logic would need some tweaking to deal with that, though, as it defaults to pixels.

**Comment by skosch** [comment]
I managed to make it work. Turns out this can be done purely in CSS, although it's quite hacky: http://stackoverflow.com/questions/17067294/html-table-with-100-width-with-vertical-scroll-inside-tbody

**Comment by bebraw** [comment]
@skosch Ok, cool. It would be great if you could do a small doc PR and refer to that. 👍
