### ISSUE TITLE
Sort function error with Tree table

### ISSUE THREAD

**Issue by cnaa97** [reactabular/reactabular#284]
Recently I used your thankful project. Thanks again. 

In tree table with sort, something error occur 

scenario is...
1. In tree table, first click 'sort'. (table header part)
2. tree Expand, Collapse doesn't work. 
3. when I don't click sort, tree table is work. (Expand, Collapse) 
4. ([Your example code](https://reactabular.js.org/#/data/tree) same thing happened.) 

dev console message here. 
![screen shot 2017-02-14 at 10 49 29 am](https://cloud.githubusercontent.com/assets/7259107/22911485/4e108390-f2a3-11e6-8f61-175495adc531.png)

I have a several choices. 
the first, disable sort function in tree table. using sort function is only enable default table.

I don't know what is best choice. Is it possible to using sort in tree table?

Please commend to me. Thanks.

**Comment by bebraw** [comment]
`sort.sorter` was missing `sort: orderBy` in the example. Fixed now. Thanks for the report. 👍
