### ISSUE TITLE
Change specific row background with rowKey

### ISSUE THREAD

**Issue by volgabar** [reactabular/reactabular#289]
Hi,
I have a check process for my data. When I pushed check button, my api returns errors. Then i want to toggle this faulty rows backgrounds red with rowkey. Do you know how i can do it ?

Thanks.

**Comment by bebraw** [comment]
Hi,

Check the [`onRow` handler](https://reactabular.js.org/#/table/styling). If you can stash the error status per row, you can alter style per row at `onRow`.
