### ISSUE TITLE
How to use dynamic rowkey for reactabular component

### ISSUE THREAD

**Issue by mstfbirinci** [reactabular/reactabular#290]
Hi,
We have created a component include reactabular table with some properties with rowkey and rows.

<GridData rows={rows} rowKey={'uniqueKey'}/>

Our aims is use this as a component . And we have different rows and rowkey. For example in our first data contains uniqueKey1 and the second data contains uniqueKey2. Actually we want to use Reactabular as a component for different rows data. But when we try to edit row we can't determine row's rowkey.

<img width="468" alt="rowkey" src="https://cloud.githubusercontent.com/assets/19333959/24706240/aff82ad6-1a17-11e7-9710-3c6a2bb229be.PNG">

When we click to a column we need to give that uniquekey dynamically to onActivate event but we can't. 

Thank you,

**Comment by bebraw** [comment]
Hi,

Note that `rowKey` accepts a function. I think you could do some customization there.
