### ISSUE TITLE
Display selected rows only

### ISSUE THREAD

**Issue by nextofsearch** [reactabular/reactabular#291]
Hi,

I am trying to figure out how to display selected rows only if a user clicks on a button. Is there an example for it? Thanks,

**Comment by bebraw** [comment]
Can you give a little visual example? Display as in how?

**Comment by nextofsearch** [comment]
@bebraw 

Please check out this [link](http://www.ec2instances.info/) If you click a row in the table, it is highlighted then you can display the selected rows only if you click a button labeled "Compare Selected"

**Comment by bebraw** [comment]
Yeah, you can do this through `onRow`. You should capture `onClick` there and set row state. Then toggle row class based on the state and use it however you like.
