### ISSUE TITLE
Table.Body - Missing valid rowKey! When header is not the same as label

### ISSUE THREAD

**Issue by Shooshte** [reactabular/reactabular#292]
I have the following column definition:

```
{
          property: 'referenceNumber',
          header: {
            label: 'Reference Number'
          },
          cell: {
            transforms: [
              value => ({
                  onClick: () => console.log(value)
              })
            ]
          }
}
```

And I am passing the following row:

```
{
     print: "PRINT ME",
     id: "Order.548a4a29-1df1-45fc-9b35-4ff5d9fd9716",
     cadastralNumber: "6001209.143.1",
     address: "Nowhere street 987",
     applicant: "4", 
     referenceNumber:"20170407-548a4a29-1df1-45fc-9b35-4ff5d9fd971622"
}
```

But I am getting the following warning:

> Table.Body - Missing valid rowKey! 
> Object {print: "PRINT ME", id: "Order.929f1399-2d1d-40b0-99ba-f5a23b36eac1", cadastralNumber: "6001209.143.1", address: "Nowhere street 987", applicant: "1"…}address: "Nowhere street 987"applicant: "1"cadastralNumber: "6001209.143.1"id: "Order.929f1399-2d1d-40b0-99ba-f5a23b36eac1"print: "PRINT ME"referenceNumber: "20170407-929f1399-2d1d-40b0-99ba-f5a23b36eac108"status: "PAID"timeCreated: "2017-04-07T08:59:35.000"__proto__: Object 
> Reference Number

The weird thing is that the rest of my columns have custom headers as well, but I am getting no warning there, for instance:
```
{
    property: 'print',
        header: {
    label: ''
    },
    cell: {
        transforms: [
            value => ({
                onClick: () => alert('clicked label')
            })
        ]
    }
}
```

And if I change the header label to referenceNumber the warning is gone.

**Comment by bebraw** [comment]
Hi,

I'm missing the React definition as that's where `rowKey` is set. Hard to say anything concrete without that.

**Comment by Shooshte** [comment]
This was my table definition:
```
 <Table.Provider className="ui table padded" columns={columns}>
            <Table.Header />
            <Table.Body rows={rows} rowKey={columns[1].header.label} />
</Table.Provider>
```
After changing the rowKey to rowKey="id", the warning is gone. Does this mean it will take the id key from the row object and use it as the rowKey?

**Comment by bebraw** [comment]
Yeah, `rowKey="id"` is a good choice as those ids are likely unique. This is what the warning is about. 👍
