### ISSUE TITLE
Is it possible to make two more nested column ?

### ISSUE THREAD

**Issue by cnaa97** [reactabular/reactabular#301]
I checked [nested-columns](https://reactabular.js.org/#/column-definition/nested-columns) guide. 

But sample code texted only two nested column. like this.
![screen shot 2017-05-25 at 1 39 13 pm](https://cloud.githubusercontent.com/assets/7259107/26436170/98d4d192-414f-11e7-85a5-f10daad8e38b.png)

It is possible to make more nested column?

here is sample
<img width="444" alt="screen shot 2017-05-25 at 1 43 35 pm" src="https://cloud.githubusercontent.com/assets/7259107/26436261/2d609648-4150-11e7-9cfe-eb21550aa79b.png">

**Comment by bebraw** [comment]
The definition is recursive so it should work, yeah. You can have `children` inside `children` etc.

**Comment by cnaa97** [comment]
Here is my code. but looks some trouble. 

Table body's data is worked, but Header's columns doesn't work.

```js
const columns = {
    header: {label: "TEST"},
    children: [
        header: {label: "RECENT"},,
        children: [
            {property: "testCnt", header: { label: "testCnt"}},
            {property: "exceptionCnt", header: { label: "exceptionCnt"}}
        ]
    ]
};
```

```
const resolvedColumns = resolve.columnChildren({ columns }),
            resolvedColumnsHeaderRows = resolve.headerRows({ columns });

return (
    <table.Provider columns={resolvedColumns}>
        <Sticky.Header
            headerRows={resolvedColumnsHeaderRows} />
           ...
```

Third column not shown.

![screen shot 2017-05-25 at 2 24 14 pm](https://cloud.githubusercontent.com/assets/7259107/26437094/0034803e-4156-11e7-8823-eaa4ed05a424.png)

I think `resolvedColumnsHeaderRows` looks weird.

here is captured image, `resolvedColumnsHeaderRows` in console
My guess, Array type `resolvedColumnsHeaderRows` have to 3 length. but resolved header column's length is just 2.

![screen shot 2017-05-25 at 2 26 00 pm](https://cloud.githubusercontent.com/assets/7259107/26437139/3b76bafe-4156-11e7-8fce-4b3a5ff40bef.png)

**Comment by bebraw** [comment]
Ok, it might be some bug in the header rendering code then. I don't have time/budget to fix sadly but if someone wants to PR, I don't mind reviewing.

**Comment by bebraw** [comment]
Fixed in https://github.com/reactabular/table-resolver/pull/3.
