### ISSUE TITLE
Table not rendering properly

### ISSUE THREAD

**Issue by tayzee** [reactabular/reactabular#303]
Hi There, 

I have installed the reactabular component into my project and for some reason its not rendering properly (as per attachment). Please can you tell me why? 

I am using the AlignedTable example from your documentation, have tried other examples too, it always renders like this.

Secondly, is there a way to select a row with reactabular?

![screen shot 2017-06-06 at 11 30 58](https://cloud.githubusercontent.com/assets/6752666/26823251/44590d38-4aad-11e7-97d9-0e3158a5485f.png)

**Comment by bebraw** [comment]
It could be something styling related. Please check the CSS rules that get applied carefully. There's a lot of flexibility when it comes to that.

> Secondly, is there a way to select a row with reactabular?

See [the selection API](https://reactabular.js.org/#/features/selection).

**Comment by tayzee** [comment]
is the default styling not built into the component?

Could it be that i am running this component within a bootstrap 4 project and that its defaulting the styling to the bootstrap styling?

**Comment by bebraw** [comment]
There's no default styling, correct. I have some suggested styles [here](https://github.com/reactabular/reactabular/blob/master/style.css).

You can apply Bootstrap styling by attaching classes through the `components` interface. There's a small example of that in the documentation.

**Comment by tayzee** [comment]
Ok, so a little more reading wouldve found me the answers! Thanks for answering anyway :)

**Comment by tayzee** [comment]
Sorry, now that i got the styling to work, one more question:
Is it possible to use % values for width and height?

**Comment by bebraw** [comment]
> Is it possible to use % values for width and height?

I think it should since CSS supports relative widths.
