### ISSUE TITLE
Resizing columns for Nested Table

### ISSUE THREAD

**Issue by cnaa97** [reactabular/reactabular#307]
Table that I implemented need to support Nested columns and Resizing column both at the same time. 

But Resizing columns, doesn't support nested columns. like this.

![screen shot 2017-06-21 at 11 15 11 am](https://user-images.githubusercontent.com/7259107/27364011-ef9d5066-5672-11e7-8d05-9fcc939c7db9.png)

General table (not nested columns, just one line column) is OK. 
In Resizing Columns function, It looks need to implement for nested columns.

I check some code,

**Comment by cnaa97** [comment]
First column is detected. and First column's body is resizing work. but 

In `helper.js`, didn't detect children's header and body column. 

![screen shot 2017-06-21 at 11 25 18 am](https://user-images.githubusercontent.com/7259107/27364243-5895983e-5674-11e7-8a19-be4173004de1.png)

![screen shot 2017-06-21 at 11 23 57 am](https://user-images.githubusercontent.com/7259107/27364244-589ab8a0-5674-11e7-9371-84b6308ee480.png)

**Comment by bebraw** [comment]
I think we fixed this. Time to close.
