### ISSUE TITLE
Horizontal scroll of header and body not synchronized for resizable columns

### ISSUE THREAD

**Issue by ferdud** [reactabular/reactabular#309]
Hello,
I just find out that horizontal scroll of header is not synchronized with with that of body. The other way around as well. I have seen this in your resize example, that after resizing table so it's wider than container scroll is not working properly(as it is in virtualization example).
Is it a problem of example(if so i don't see it), or of table.
Thanks for response in advance.
Ferdinand

**Comment by bebraw** [comment]
Yeah, this might need some code fix (missing handler). PR most welcome!

**Comment by dtaub** [comment]
I know I haven't gotten around to fixing it yet but is this a duplicate of #282?

**Comment by bebraw** [comment]
Yeah, fair point. Let's close.
