### ISSUE TITLE
Rerender table on data change, is it through shouldComponentUpdate?

### ISSUE THREAD

**Issue by zelanter** [reactabular/reactabular#311]
Hi,

my data changes, comes from external json, stored in redux store and changes as actions are dispatched. I am trying to get the table to rerender upon data change, which is passed as props and is used in row composition.
I saw some examples about shouldComponentUpdate as body/row wrapper, also tried through componentWillReceiveProps(), but I just can't seem to get the table to refresh.

What would be the standard way to refresh the table on data change?

Thank you

**Comment by bebraw** [comment]
I think you may have to override the default SCU. See [here](https://reactabular.js.org/#/table/overriding-should-component-update). It should pick up row level changes by default but maybe there's something else going on and you have to account for that.

**Comment by zelanter** [comment]
Yes, that's the example I looked at and tried to reproduce, but I did not see that it was picking up props changes. Will it detect custom props changes? Also, for body wrapper it was clear, but for row wrapper, I tried but I was not sure how to combine it with dnd.Rows.

Also, the initial use of my props is in the constructor, where it sets the version of state variable rows, if there a way to create that relationship between rows and my data (through props) at rendering level, I guess it would pick up automatically. Also I tried to reset state in componenWillReceiveProps, replicating the code from constructor, but it was giving me error about missing column. Are we supposed to be able to redefine rows? I know for columns I don't have issues, I resize them dynamically and it reflects in table.

Is any of what I am mentioning supposed to work and I am just doing it wrong?

Thanks

**Comment by zelanter** [comment]
Now I can clearly see it is not seeing my component level props, and if I try to explicitly put my prop in Table.Body it gets rejected. For sure I am not doing this the right way, trying to understand how I can achieve that (associating my table json data to the table in such a way that it will refresh the table when data changes).

**Comment by bebraw** [comment]
Hi,

I would need a small example to run to tell what's going on. You could disable SCU behavior temporarily entirely as that's one possible source of the problem. You will also want to validate that the table gets the right data when the JSON changes. Maybe it has something to do with the column definition too?

**Comment by zelanter** [comment]
Hi,

I can confirm that state properly gets updated at page level, and issue is how to get the table to react to it. I feel the way I made it does not create a strong enough connection between that external data and the row, since my external data is only used in constructor, and constructor would be called only once, so rerendering does not update the table data.

Basically, I am very confident that if relationship between row and my data is enforced in render method, it would be very easy to get the table to update. However, doing that requires a much deeper understanding of how ReactTabular works internally than I currently do, hopefully you know a proper way to do this.

Here is a simplified version of my code to better illustrate what I am doing (which is directly based on your examples and I adapt to my needs):

```
// constructor
//...
    const columns = this.getColumns();
    const rows = resolve.resolve({ columns })(
      this.props.myTableData);

    this.state = {
      searchColumn: 'all',
      query: {},
      sortingColumns: null,
      rows,
      columns
}
//...
// getColumns
  getColumns() {
    return [
      {
        property: 'firstColumn',
        props: {
          style: { minWidth: columnBaseWidthFirstColumn, width: columnBaseWidthFirstColumn }
        },
        header: {
          label: 'First Column'
        },
        cell: {
          formatters: [
            tree.toggleChildren({
              getRows: () => this.state.rows,
              getShowingChildren: ({ rowData }) => rowData.showingChildren,
              toggleShowingChildren: rowIndex => {
                const rows = cloneDeep(this.state.rows);

                rows[rowIndex].showingChildren = !rows[rowIndex].showingChildren;

                this.setState({ rows });
              },
              // Inject custom class name per row here etc.
              props: {}
            })
          ]
        },
        visible: true
      },
      {
        property: 'secondColumn',
        props: {
          style: { minWidth: columnBaseWidthSecondColumn, width: columnBaseWidthSecondColumn }
        },
        header: {
          label: 'SecondColumn'
        },
        visible: true
      }
    ];
  }
  //render()
  //...
      const {
      searchColumn, columns, sortingColumns, query
    } = this.state;
    const visibleColumns = columns.filter(column => column.visible);

    const rows = compose(
      tree.filter({ fieldName: 'showingChildren' }),
      tree.wrap({
        operations: [
          sort.sorter({
            columns,
            sortingColumns,
            sort: orderBy
          })
        ]
      }),
      tree.search({
        operation: search.multipleColumns({ columns, query })
      })
    )(this.state.rows);

    const components = {
      body: {
        //wrapper: BodyWrapper,
        row: dnd.Row // how am I supposed to combine this with a row wrapper?
      }
    };
//...
return (
//...
          <Table.Provider
            className="pure-table pure-table-striped"
            style={{ 'fontSize': this.state.tableTextFontSize }}
            components={components}
            columns={this.state.columns}//{visibleColumns}
          >
            <Table.Header />
            <Table.Body rows={rows} rowKey="id" onRow={this.onRow} />
          </Table.Provider>

)
```

Also to provide some background information on what I am doing, I am basically building a table that uses the tree structure and the drag and drop, but I am only taking advantage of the fact id is exposed, then I drop to a custom drop zone and go from that. That part is working fine so far.

Thanks

**Comment by bebraw** [comment]
Can you show where/how you fetch the external data?

**Comment by zelanter** [comment]
Data is passed as props by the parent of the component in which the table is rendered. Data itself is initially fetched from a json file by a redux middleware, and after that the other changes are internal, events from within the page trigger redux actions that modify the data.

I don't have any doubt that the page is receiving the updated state from the redux store. For example, I am checking in componentWillReceiveProps and I clearly see the new state being sent to the component.

I can show code if necessary, but from my point of view issue is that my external data is only explicitly used in constructor, so I tried to reset the state when props change, but I get "Error: resolve - Missing columns!" (I am doing the same thing I am doing in constructor for rows), tried inside of componentWillReceiveProps and componentDidUpdate, but both giving the same error.

**Comment by bebraw** [comment]
Hi,

I understand now. It's good to remember the constructor gets called only when a component is mounting. You should see React lifecycle methods and do a resolve pass when rows change. Otherwise you'll miss that and the table won't work as you expect.

**Comment by bebraw** [comment]
About the error, validate that `const columns = this.getColumns();` returns something sensible. One option would be to push resolve to render just to get it working before optimizing.

**Comment by zelanter** [comment]
Oh boy, it seems I had not wrapped columns in {} when updating rows and calling resolve.resolve in componentDidUpdate, it's now refreshing the table. Sorry about that, really is my bad. The other solutions you proposed, I am not sure I understand how to achieve those.

Now I realise the way it refreshes the data is not what I am looking for. No Data gets deleted or added, only some column values change in existing rows, and I need to persist the state, like scrolling position, tree status, etc., so back to the drawing board. If I copy current rows and update the rows manually and then set the state to that, without doing a new resolve, will my table refresh without resetting all trees and positions?

Thanks again.

**Comment by bebraw** [comment]
> If I copy current rows and update the rows manually and then set the state to that, without doing a new resolve, will my table refresh without resetting all trees and positions?

You need `resolve` to inject `_index` to the data. The underlying logic (dnd) relies on that.

Please note that this library is not under active maintenance and I'm thinking of dropping support entirely as there's no commercial demand whatsoever (doing this support work is losing money/time). So it may be a good idea to explore better supported alternatives.

**Comment by zelanter** [comment]
I use your drag, but not your drop, I don't drop in same table, I drop in other components elsewhere in the page, so I don't think resolve is needed but I'll have to try it out (to see if I can update a few columns and that state, tree, scrolling) will persist). 

A few weeks back I did ask about that (if using this for new projects was a good idea) and your answer was that you were in minimal support mode, that PRs are welcome and that you could recommend that I fork your project and start from there.

I like your project, but what I find the hardest with it is the documentation. I am not saying documentation is bad, it provides enough examples to get started, but the way it is built does not make learning easy, at least for me. So to sum up the situation, if I stick with this, there is a big possibility I will be on my own?

My next steps would be heavy customization (inserting links, using left/right click, custom style based on dynamic flags that change as actions get triggered, etc.), so there is a big chance I'd have more questions for you, so maybe your timing is right :). If this loses you time and money and there is no benefit at all for you, then I'd feel bad keeping this up and harassing you with questions.

In any case, whatever your decision is, thanks again for the help and support and I hope I was not too annoying with my questions.

**Comment by bebraw** [comment]
> I use your drag, but not your drop, I don't drop in same table, I drop in other components elsewhere in the page, so I don't think resolve is needed but I'll have to try it out (to see if I can update a few columns and that state (tree, scrolling) will persist).

Alright.

> I like your project, but what I find the hardest with it is the documentation. I am not saying documentation is bad, it provides enough examples to get started, but the way it is built does not make learning easy, at least for me. So to sum up the situation, if I stick with this, there is a big possibility I will be on my own?

Basically I can provide an answer every now and then but to truly help I would need some code to run. Otherwise it's guesswork.

To truly understand what's going under the hood it's likely a good idea to spend some time with the code. There's not much of it despite the amount of packages. That will help you understand how it all goes together. Every part of the design is there for some specific reason.

> My next steps would be heavy customization (inserting links, using left/right click, custom style based on dynamic flags that change as actions get triggered, etc.), so there is a big chance I'd have more questions for you, so maybe your timing is right :). If this loses you time and money and there is no benefit at all for you, then I'd feel bad keeping this up and harassing you with questions.

If it's something business-related, maybe you could look into getting your company to sponsor some of this work. But yeah, now the project is literally losing money as I don't have an employer and time I use is my own.

It's that customization part where reactabular begins to shine assuming you get the other problems tackled first. It's not the easiest to pick up but I tried to design it so that it doesn't get in your way when a weird requirement comes your way.

**Comment by bebraw** [comment]
Time to close. Please open separate issues for further questions.
