### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by bratukham** [reactabular/reactabular#313]
It would be nice to have typings for better compatibility with TypeScript.
For example "@types /reactabular", "@types /sortabular", etc.

Do you have any plans to make it possible?

**Comment by bebraw** [comment]
Hi,

There's no active development as the project ran out of funding. If someone wants to submit a PR, I don't mind helping to get it merged, though.

**Comment by bebraw** [comment]
I think we would have to rewrite portions in TypeScript to get this done. Maintaining separate type definitions would be likely too much. I can accept PRs for this work. Time to close as I won't do it (unless funding appears).
