### ISSUE TITLE
Reactabular performance issue.

### ISSUE THREAD

**Issue by AbhilashSunkam** [reactabular/reactabular#314]
I had implemented a table using reactabular which has more than thousands of rows. The issues that I face is,
1) Visibility toggle is very slow (Takes more than 1-2 secs to take effect)
2) Search filter on each column is very very slow
I see the above features work very fast when there are lesser number of rows in the table. I could see the performance going down when there are many rows. Why is this happening? Any optimizations possible when there are many rows?

**Comment by bebraw** [comment]
Did you implement virtualization as instructed in the documentation?
