### ISSUE TITLE
table-resovler is not efficient

### ISSUE THREAD

**Issue by redguardtoo** [reactabular/reactabular#315]
When there are more than 2000 rows and 100 columns, the table rendering is 10 times slower.

I did profiling and found most time is spent on table-resolver.

It's kind of too much computing in order to get rowIndex. I worked around  it by manually add rowIndex attribute to each row before feeding data into reactaublar.

**Comment by bebraw** [comment]
That's a fair point. If you have time, you could write a benchmark suite against [the project](https://github.com/reactabular/table-resolver). It's fairly well tested so you could try to optimize it after that. Maybe there are some obvious fixes to perform.

**Comment by redguardtoo** [comment]
Cool. Thanks
