### ISSUE TITLE
Warning message for VirtualizedBody forceUpdate and setState when navigating between pages

### ISSUE THREAD

**Issue by miachenmtl** [reactabular/reactabular#319]
I'm getting this error message when navigating between pages that have Reactabular Virtualized tables on them:

> Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the VirtualizedBody component.

Or the same error message with `setState` instead of `forceUpdate`. Upon further investigation, I think the issue can be resolved by clearing the timeout that's set in `checkMeasurements` in a `componentWillUnmount` method. I can submit a PR.

**Comment by bebraw** [comment]
Sure, a PR would be great. Like you said, it's missing a clear. That's all.

**Comment by bebraw** [comment]
Forgot to close this during the PR.
