### ISSUE TITLE
reactabular-dnd - Wait for react-dnd fixes

### ISSUE THREAD

**Issue by bebraw** [reactabular/reactabular#325]
Currently dnd bits don't work ideally with React 16 due to https://github.com/react-dnd/react-dnd/issues/896 . We have to wait for that work to go through and then do a small update here (likely only dep upgrade).

**Comment by zelanter** [comment]
The fix is now available for react-dnd.

**Comment by bebraw** [comment]
@zelanter Cool. I'll do a little update next week. Maybe there's something else to change as well.

**Comment by bebraw** [comment]
@zelanter Yeah, confirmed. The PR wasn't enough. There's something else going on. The problem is that I don't know if it's something in **react-dnd** or here and don't have time to debug.

**Comment by zelanter** [comment]
@bebraw I have some good news. It turned that that for me, issue was with how I was declaring the body wrapper (following examples found in documentation body wrapper was defined as functional component). I redefined it as class and now it appears to be working fine, warning is gone.

For reference:

```
    const bodyWrapper = class extends React.Component {
      shouldComponentUpdate(nextProps, nextState) {
        return nextProps.rows !== this.props.rows;
      }
      render() {
        return <tbody {...this.props} />;
      }
    };
```
Thanks

**Comment by bebraw** [comment]
@zelanter Ah, I see... So maybe it's just a documentation fix and a big warning.

**Comment by sapegin** [comment]
I’ve checked all examples in DND section with react-dnd@2.5.4 and don’t see any warnings. Looks like we can safely close this issue.
