### ISSUE TITLE
Switch to Treetabular ^3.5

### ISSUE THREAD

**Issue by thoaionline** [reactabular/reactabular#329]
At the moment, this component has a dependency on `treetabular` 3.4.x, which only supports react 15. The new version of Treetabular support react 16 (latest stable) and should be used instead.

Is there a reason we are requiring `"treetabular": "^3.4.0"` instead of just `"treetabular": "^3.4"`?

**Comment by bebraw** [comment]
This should be a simple fix. Please PR. I might fix it too at some point.

**Comment by thoaionline** [comment]
PR created #330
