### ISSUE TITLE
Style cell based on values 

### ISSUE THREAD

**Issue by a2441918** [reactabular/reactabular#341]
Hi, I would like to implement styling for cells based on values. If a cell has a value within a range, it should have different background colors.

Here is my implementation.

		{
		    property: 'percentage_compliant',
		    header: {
		      	label: 'Percentage Compliant',
		       	formatters: [label => this.sortFormatter(label, 'percentage_compliant')],
		       	transforms: [
		       		property => ({
		           		onClick: () => this.columnClick('percentage_compliant')
		       		})
		       	]
		    },
		    cell: {
		       	formatters: [this.percentageFormatter],
		       	transforms: [
		       		value => this.styleFormatter(value)
		       	]
			}
		}

	  styleFormatter = (cell) => {
	    if (cell >= 95) {
	      return <span className="green-background">{cell}</span>;
	    } else if (cell < 95 && cell > 79) {
	      return <span className="yellow-background">{cell}</span>;
	    }
	    return <span className="red-background">{cell}</span>;
	  };

Please advice.

**Comment by a2441918** [comment]
Yeah @bebraw . I am doing it on the cell level as per my implementation. But not getting the right output.

**Comment by bebraw** [comment]
@a2441918 Are you sure your data is correct and cast to integers? What if you `console.log` cell? The cell formatter looks fine to me but I would need something to run to say what the exact issue is.

**Comment by a2441918** [comment]
![image](https://user-images.githubusercontent.com/4927454/38581452-ef44a7aa-3cda-11e8-917f-074799cf5ede.png)

@bebraw This is what I get in the DOM.

I get the value in the cell, like 75 or 60 or 50 when I console.log(cell) inside styleFormatter. My logic seems right, maybe I need to do with props?

**Comment by a2441918** [comment]
I checked the typeof cell and it showed me as a string. I then typecasted it to an integer using cell= parseInt(cell) and still no colors.

**Comment by a2441918** [comment]
@bebraw Here it is
https://codesandbox.io/s/914qplyjwp

**Comment by bebraw** [comment]
@a2441918 Can you do a GitHub repository?

I think I know why it fails btw. There's a big difference between transforms and formatters. Transforms adjust just props. See https://reactabular.js.org/#/column-definition/transforms . So you could do a transform like:

```javascript
styleTransform = (cell) => {
  if (cell >= 95) {
    return { className: 'green-background' }
  }

  ...
};
```

Formatters get applied *inside* transforms and you can have multiple of each as they get applied in order.

I think doing this change might fix your issue.
