### ISSUE TITLE
reactabular-table components vs renderers prop

### ISSUE THREAD

**Issue by priley86** [reactabular/reactabular#348]
Hi,

I just wanted to report that the change to `renderers` seemed to actually be a breaking change for us. The `components` prop no longer renders our column header/rows definitions correctly after the semantic update from `^8.12.0` to `^8.13.0`. This was only noticed at runtime where `process.env.NODE_ENV` is `production` - our dev build was unaffected.

We have updated to the `renderers` prop but you may want to look into a fix if you are planning to continue support for the `components` prop.

reference: https://github.com/patternfly/patternfly-react/pull/357

**Comment by bebraw** [comment]
Thanks for the heads-up. It should be fixed now.

Note that I'm doing a major rewrite at https://github.com/reactabular/reactabular/pull/345 . It should simplify things quite a bit.

**Comment by priley86** [comment]
thanks a lot @bebraw 👍
