### ISSUE TITLE
Reactabular-dnd should expose hover in some way

### ISSUE THREAD

**Issue by sikolio** [reactabular/reactabular#357]
Hello,

We want to style in some way the target of the row being moved, right now because of the implementation missing the monitor option from `react-dnd` we can not do this.
 
```
const dropTarget = DropTarget( // eslint-disable-line new-cap
  DragTypes.ROW, rowTarget, connect => ({
    connectDropTarget: connect.dropTarget()
  })
);
```

What I want to propose is to pass in some way a 'hover' class/prop to add to the target and that sort of things.

Thanks!

**Comment by bebraw** [comment]
Done in #358.
