### ISSUE TITLE
Reference column property

### ISSUE THREAD

**Issue by caraclarke** [reactabular/reactabular#364]
Working with reactabular I have run into a question about referencing column properties from within the same object. I am trying to find a way to avoid calling a function that checks visibility twice in my column definition object. I have the following code right now (snippet of full object with the relevant information)

```
{
 property: 'id',
 header: {
  label: 'your id'
 },
 internalProps: {
  visible: GetColumnVisibility('id', userID)
 },
 props: {
  classes: [
    `visibilityColumn ${
      GetColumnVisibility('id', userID) ? '' : 'hidden'
    }`
  ]
}
```

I would like to be able to do something like:

```
internalProps: {
  visible: GetColumnVisibility('id', userID)
 },
 props: {
  classes: [
    `visibilityColumn ${
      internalProps.visible ? '' : 'hidden'
    }`
  ]
}
```

Does reactabular have a way to support that syntax? Thanks

**Comment by bebraw** [comment]
There's no specific support for this. One option would be to `memoize` `GetColumnVisibility` so the double call doesn't matter.
