### ISSUE TITLE
'reactabular-virtualized' is shaking in the mobile environment.

### ISSUE THREAD

**Issue by bolam-o** [reactabular/reactabular#386]
Hello, I'm using reactabular + reactabular-virtualized at my list component.

I implemented the same as the example below, but when scrolling in the mobile environment, there was a rocking like vibration.
The following example was checked in the mobile environment and found the same problem as mine.

https://reactabular.js.org/#/features/virtualization

If the image looks slow, I would appreciate it if you click and look closely.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/61655667/112414963-58260780-8d66-11eb-8ee5-3f49bdb64cdf.gif)

**Comment by bolam-o** [comment]
I am applying the following settings.

```
"react": "^16.2.0",
"react-dom": "^16.2.0",
"reactabular-sticky": "^8.14.0",
"reactabular-table": "^8.13.0",
"reactabular-virtualized": "^8.18.0",
```

**Comment by bebraw** [comment]
Hi,

Can you set up a standalone example on something like codesandbox? It's hard to say what's the problem especially if you are following the official examples.

Note that I am not maintaining this project actively due to lack of funding but I can still have a quick look to see if it's something obvious.

**Comment by bebraw** [comment]
Nevermind, I can see the issue on mobile Safari against the official example. It might be a bug in virtualization.

**Comment by bolam-o** [comment]
Thank you so much for your interest in my issue.

The problem I posted can also be confirmed in the example in the official documentation. My environment is a chrome browser.

I'm also looking for a solution, but I want to find an answer quickly. 😂

**Comment by bebraw** [comment]
I can see the issue in the https://reactabular.js.org/#/features/sticky example as well on mobile Safari (not on my desktop Chromium, though). That narrows it down to sticky code.

I have the implementation here: https://github.com/reactabular/reactabular/tree/master/packages/reactabular-sticky . I think you could replace that with another synchronization mechanism between the header and the body. It's not much code and you could try to do this against the architecture I have in place or on top of Reactabular if you have a bit of time.

**Comment by bebraw** [comment]
Did you find a solution? Likely it's worth keeping open as it's some issue within Safari to solve.
