### ISSUE TITLE
Arrows for Ascending/Descending sort are opposite

### ISSUE THREAD

**Issue by jsanderi** [reactabular/reactabular#388]
Using [this example](https://reactabular.js.org/#/examples/all-features): 

Clicking at the sort button once triggers an Ascending sort, but the icon points downwards indicating a descending sort
Clicking again switched to descending sort, but now the arrow points up again :)

I have not seen any other software that behaves like this, and for example in Microsoft Excel, an arrow up is used for Ascending sort.

**Comment by bebraw** [comment]
Thanks, I fixed the CSS at source level.

It looks like I cannot deploy the project and update the site at the moment, though, as dependencies are so outdated.
